In [ ]:
import pandas as pd

In [ ]:
sales = pd.read_csv("/content/sales_daily.csv")

In [ ]:
sales.shape

(20931, 6)

In [ ]:
sales.head()

         date  sku_id  units_sold    revenue    price  promo_flag
0  2025-01-01  SKU001        52.0  245974.56  4730.28           0
1  2025-01-02  SKU001        69.0  326389.32  4730.28           0
2  2025-01-03  SKU001        49.0  231783.72  4730.28           0
3  2025-01-04  SKU001        74.0  350040.72  4730.28           0
4  2025-01-05  SKU001        43.0  203402.04  4730.28           0

In [ ]:
import pandas as pd

sales = pd.read_csv("/content/sales_daily.csv")

In [ ]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20931 entries, 0 to 20930
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        20931 non-null  object
 1   sku_id      20931 non-null  object
 2   units_sold  20861 non-null  float64
 3   revenue     20931 non-null  float64
 4   price       20881 non-null  float64
 5   promo_flag  20931 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 981.3+ KB

In [ ]:
sales.isnull().sum()

date           0
sku_id         0
units_sold    70
revenue        0
price         50
promo_flag     0
dtype: int64

In [ ]:
sales.duplicated().sum()

np.int64(25)

In [ ]:
sales.dtypes

date           object
sku_id         object
units_sold    float64
revenue       float64
price         float64
promo_flag      int64
dtype: object

In [ ]:
sales[['units_sold', 'revenue', 'price']].describe()

         units_sold       revenue         price
count  20861.000000  2.093100e+04  20881.000000
mean      60.835339  2.354509e+05   4072.122821
std       34.379807  2.001104e+05   2166.821152
min        1.000000  7.387170e+03    637.850000
25%       34.000000  8.912190e+04   1844.520000
50%       59.000000  1.567842e+05   4088.420000
75%       83.000000  3.273227e+05   5788.570000
max      840.000000  1.484829e+06   8525.330000

In [ ]:
sales[sales['units_sold'] > 200].sort_values('units_sold', ascending=False).head(20)

             date  sku_id  units_sold     revenue    price  promo_flag
13533  2026-02-01  SKU026       840.0   707843.85  6741.37           0
11615  2025-04-03  SKU023       680.0   347515.70  4088.42           0
7640   2025-10-23  SKU015       552.0    99184.05  1437.45           0
14550  2025-11-18  SKU028       504.0    43304.94   687.38           0
18241  2026-05-24  SKU035       504.0   364679.91  5788.57           0
5127   2026-01-03  SKU010       416.0   443317.16  8525.33           0
13671  2026-06-19  SKU026       233.0  1445080.07  6741.37           1
16007  2025-11-23  SKU031       232.0    78861.81  2955.84           1
5820   2026-06-12  SKU011       226.0   660746.89  3177.89           1
4208   2026-06-12  SKU008       223.0  1484829.09  7237.42           1
10161  2025-08-15  SKU020       210.0   980744.10  4670.21           0
4213   2026-06-17  SKU008       202.0  1345002.13  7237.42           1
4215   2026-06-19  SKU008       202.0  1345002.13  7237.42           1

In [ ]:
sales['calculated_revenue'] = sales['units_sold'] * sales['price']

sales['revenue_difference'] = (
    sales['revenue'] - sales['calculated_revenue']
)

sales[['date', 'sku_id', 'units_sold', 'price',
       'revenue', 'calculated_revenue',
       'revenue_difference']].head(10)

,date,sku_id,units_sold,price,revenue,calculated_revenue,revenue_difference
0,2025-01-01,SKU001,52.0,4730.28,245974.56,245974.56,0.000000e+00
1,2025-01-02,SKU001,69.0,4730.28,326389.32,326389.32,0.000000e+00
2,2025-01-03,SKU001,49.0,4730.28,231783.72,231783.72,0.000000e+00
3,2025-01-04,SKU001,74.0,4730.28,350040.72,350040.72,0.000000e+00
4,2025-01-05,SKU001,43.0,4730.28,203402.04,203402.04,2.910383e-11
5,2025-01-06,SKU001,56.0,4730.28,264895.68,264895.68,0.000000e+00
6,2025-01-07,SKU001,46.0,4730.28,217592.88,217592.88,2.910383e-11
7,2025-01-08,SKU001,51.0,4730.28,241244.28,241244.28,0.000000e+00
8,2025-01-09,SKU001,65.0,4730.28,307468.20,307468.20,0.000000e+00
9,2025-01-10,SKU001,70.0,4730.28,304630.03,331119.60,-2.648957e+04

In [ ]:
sales['calculated_revenue'] = sales['units_sold'] * sales['price']

non_promo_issues = sales[
    (sales['promo_flag'] == 0) &
    (sales['units_sold'].notna()) &
    (sales['price'].notna()) &
    (abs(sales['revenue'] - sales['calculated_revenue']) > 1)
]

print("Non-promo revenue inconsistencies:", len(non_promo_issues))

non_promo_issues[
    ['date', 'sku_id', 'units_sold', 'price',
     'revenue', 'calculated_revenue']
].head(20)

Non-promo revenue inconsistencies: 7

             date  sku_id  units_sold    price    revenue  calculated_revenue
5127   2026-01-03  SKU010       416.0  8525.33  443317.16          3546537.28
6520   2025-08-19  SKU013       136.0  7066.44  120129.48           961035.84
7640   2025-10-23  SKU015       552.0  1437.45   99184.05           793472.40
11615  2025-04-03  SKU023       680.0  4088.42  347515.70          2780125.60
13533  2026-02-01  SKU026       840.0  6741.37  707843.85          5662750.80
14550  2025-11-18  SKU028       504.0   687.38   43304.94           346439.52
18241  2026-05-24  SKU035       504.0  5788.57  364679.91          2917439.28

In [ ]:
sales['sku_id'].unique()

array(['SKU001', 'SKU002', 'SKU003', 'sku003', 'SKU004', 'SKU005',
       'SKU006', 'SKU007', 'SKU008', 'SKU009', 'sku009', 'SKU010',
       'SKU011', 'SKU012', 'SKU013', 'SKU014', 'SKU015', 'sku015',
       'SKU016', 'SKU017', 'SKU018', 'SKU019', 'SKU020', 'SKU021',
       'SKU022', 'sku022', 'SKU023', 'SKU024', 'SKU025', 'SKU026',
       'SKU027', 'SKU028', 'sku028', 'SKU029', 'SKU030', 'sku030',
       'SKU031', 'SKU032', 'sku032', 'SKU033', 'SKU034', 'sku034',
       'SKU035', 'SKU036', 'SKU037', 'SKU038', 'sku038', 'SKU039',
       'SKU040'], dtype=object)

In [ ]:
sku_master = pd.read_csv("/content/sku_master.csv")

In [ ]:
print(sku_master.shape)

(40, 6)

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
import zipfile

zip_path = "/content/Project_FORESIGHT_Synthetic_Datasets.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("/content/foresight_data")

print("Files extracted successfully!")

FileNotFoundError: [Errno 2] No such file or directory: '/content/Project_FORESIGHT_Synthetic_Datasets.zip'

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Project_FORESIGHT_Synthetic_Datasets.zip to Project_FORESIGHT_Synthetic_Datasets.zip

In [ ]:
import zipfile

zip_path = "/content/Project_FORESIGHT_Synthetic_Datasets.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall("/content/foresight_data")

print("Files extracted successfully!")

Files extracted successfully!

In [ ]:
import os

print(os.listdir("/content/foresight_data"))

['inventory_snapshots.csv', 'calendar.csv', 'README.txt', 'sales_daily.csv', 'sku_master.csv']

In [ ]:
import pandas as pd

sales = pd.read_csv("/content/foresight_data/sales_daily.csv")
sku_master = pd.read_csv("/content/foresight_data/sku_master.csv")
calendar = pd.read_csv("/content/foresight_data/calendar.csv")
inventory = pd.read_csv("/content/foresight_data/inventory_snapshots.csv")

print("All 4 datasets loaded successfully!")

All 4 datasets loaded successfully!

In [ ]:
print("Sales Daily:", sales.shape)
print("SKU Master:", sku_master.shape)
print("Calendar:", calendar.shape)
print("Inventory Snapshots:", inventory.shape)

Sales Daily: (20931, 6)
SKU Master: (40, 6)
Calendar: (546, 7)
Inventory Snapshots: (21840, 6)

In [ ]:
print("===== SALES DAILY =====")
sales.info()

print("\n===== SKU MASTER =====")
sku_master.info()

print("\n===== CALENDAR =====")
calendar.info()

print("\n===== INVENTORY SNAPSHOTS =====")
inventory.info()

===== SALES DAILY =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20931 entries, 0 to 20930
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        20931 non-null  object
 1   sku_id      20931 non-null  object
 2   units_sold  20861 non-null  float64
 3   revenue     20931 non-null  float64
 4   price       20881 non-null  float64
 5   promo_flag  20931 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 981.3+ KB

===== SKU MASTER =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku_id       40 non-null     object
 1   category     40 non-null     object
 2   subcategory  40 non-null     object
 3   launch_date  40 non-null     object
 4   unit_cost    39 non-null     float64
 5   list_price   40 non-null     float64
dtypes: float64(2), object(4)
memory usage: 2.0+ KB

===== CALENDAR =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         546 non-null    object
 1   week         546 non-null    int64
 2   month        546 non-null    int64
 3   season       546 non-null    object
 4   is_holiday   546 non-null    int64
 5   promo_event  85 non-null     object
 6   promo_flag   546 non-null    int64
dtypes: int64(4), object(3)
memory usage: 30.0+ KB

===== INVENTORY SNAPSHOTS =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21840 entries, 0 to 21839
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            21840 non-null  object
 1   sku_id          21840 non-null  object
 2   on_hand_units   21800 non-null  float64
 3   on_order_units  21840 non-null  int64
 4   lead_time_days  21800 non-null  float64
 5   reorder_point   21840 non-null  int64
dtypes: float64(2), int64(2), object(2)
memory usage: 1023.9+ KB

In [ ]:
import pandas as pd
import os

print("Files available:")
print(os.listdir("/content/foresight_data"))

sales = pd.read_csv("/content/foresight_data/sales_daily.csv")
sku_master = pd.read_csv("/content/foresight_data/sku_master.csv")
calendar = pd.read_csv("/content/foresight_data/calendar.csv")
inventory = pd.read_csv("/content/foresight_data/inventory_snapshots.csv")

print("\nSales shape:", sales.shape)
print("SKU Master shape:", sku_master.shape)
print("Calendar shape:", calendar.shape)
print("Inventory shape:", inventory.shape)

Files available:

FileNotFoundError: [Errno 2] No such file or directory: '/content/foresight_data'

In [ ]:
from google.colab import files
import zipfile
import os
import pandas as pd

# Upload ZIP
uploaded = files.upload()

# Get the uploaded filename automatically
zip_name = next(iter(uploaded))

# Extract
extract_path = "/content/foresight_data"

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(extract_path)

# Load datasets
sales = pd.read_csv(f"{extract_path}/sales_daily.csv")
sku_master = pd.read_csv(f"{extract_path}/sku_master.csv")
calendar = pd.read_csv(f"{extract_path}/calendar.csv")
inventory = pd.read_csv(f"{extract_path}/inventory_snapshots.csv")

print("SUCCESS — All datasets loaded.")
print("Sales:", sales.shape)
print("SKU Master:", sku_master.shape)
print("Calendar:", calendar.shape)
print("Inventory:", inventory.shape)

Saving Project_FORESIGHT_Synthetic_Datasets.zip to Project_FORESIGHT_Synthetic_Datasets.zip
SUCCESS — All datasets loaded.
Sales: (20931, 6)
SKU Master: (40, 6)
Calendar: (546, 7)
Inventory: (21840, 6)

In [ ]:
print("===== SALES DAILY =====")
print(sales.isnull().sum())

print("\n===== SKU MASTER =====")
print(sku_master.isnull().sum())

print("\n===== CALENDAR =====")
print(calendar.isnull().sum())

print("\n===== INVENTORY SNAPSHOTS =====")
print(inventory.isnull().sum())

===== SALES DAILY =====
date           0
sku_id         0
units_sold    70
revenue        0
price         50
promo_flag     0
dtype: int64

===== SKU MASTER =====
sku_id         0
category       0
subcategory    0
launch_date    0
unit_cost      1
list_price     0
dtype: int64

===== CALENDAR =====
date             0
week             0
month            0
season           0
is_holiday       0
promo_event    461
promo_flag       0
dtype: int64

===== INVENTORY SNAPSHOTS =====
date               0
sku_id             0
on_hand_units     40
on_order_units     0
lead_time_days    40
reorder_point      0
dtype: int64

In [ ]:
print(calendar['promo_event'].value_counts(dropna=False))

promo_event
NaN              461
Summer Sale       22
Spring Sale       19
Year End Sale     17
Black Friday      11
Festive Sale      10
New Year Sale      6
Name: count, dtype: int64

In [ ]:
print(calendar['promo_event'].value_counts(dropna=False))

promo_event
NaN              461
Summer Sale       22
Spring Sale       19
Year End Sale     17
Black Friday      11
Festive Sale      10
New Year Sale      6
Name: count, dtype: int64

In [ ]:
print(calendar['promo_event'].value_counts(dropna=False))

promo_event
NaN              461
Summer Sale       22
Spring Sale       19
Year End Sale     17
Black Friday      11
Festive Sale      10
New Year Sale      6
Name: count, dtype: int64

In [ ]:
print(calendar['promo_event'].value_counts(dropna=False))

promo_event
NaN              461
Summer Sale       22
Spring Sale       19
Year End Sale     17
Black Friday      11
Festive Sale      10
New Year Sale      6
Name: count, dtype: int64

In [ ]:
print("Sales duplicates:", sales.duplicated().sum())
print("SKU Master duplicates:", sku_master.duplicated().sum())
print("Calendar duplicates:", calendar.duplicated().sum())
print("Inventory duplicates:", inventory.duplicated().sum())

Sales duplicates: 25
SKU Master duplicates: 0
Calendar duplicates: 0
Inventory duplicates: 0

In [ ]:
print("Sales:")
print(sales['date'].min(), "to", sales['date'].max())

print("\nSKU Master:")
print(sku_master['launch_date'].min(), "to", sku_master['launch_date'].max())

print("\nCalendar:")
print(calendar['date'].min(), "to", calendar['date'].max())

print("\nInventory:")
print(inventory['date'].min(), "to", inventory['date'].max())

Sales:
2025-01-01 to 2026-06-30

SKU Master:
2024-02-14 to 2025-05-13

Calendar:
2025-01-01 to 2026-06-30

Inventory:
2025-01-01 to 2026-06-30

In [ ]:
calendar_dates = pd.to_datetime(calendar['date'])

expected_dates = pd.date_range(
    start=calendar_dates.min(),
    end=calendar_dates.max(),
    freq='D'
)

missing_dates = expected_dates.difference(calendar_dates)

print("Expected dates:", len(expected_dates))
print("Actual calendar dates:", len(calendar_dates))
print("Missing dates:", len(missing_dates))

print("\nMissing dates:")
print(missing_dates)

Expected dates: 546
Actual calendar dates: 546
Missing dates: 0

Missing dates:
DatetimeIndex([], dtype='datetime64[ns]', freq='D')

In [ ]:
print("Negative units sold:", (sales['units_sold'] < 0).sum())
print("Negative revenue:", (sales['revenue'] < 0).sum())
print("Negative price:", (sales['price'] < 0).sum())

print("Negative inventory:", (inventory['on_hand_units'] < 0).sum())
print("Negative on-order units:", (inventory['on_order_units'] < 0).sum())
print("Negative reorder point:", (inventory['reorder_point'] < 0).sum())

Negative units sold: 0
Negative revenue: 0
Negative price: 0
Negative inventory: 1
Negative on-order units: 0
Negative reorder point: 0

In [ ]:
inventory[['on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point']].describe()

       on_hand_units  on_order_units  lead_time_days  reorder_point
count   21800.000000    21840.000000    21800.000000   21840.000000
mean       40.380642       90.213187        7.800046     337.625000
std       134.315124       79.320309        3.743063     258.342293
min       -25.000000        0.000000        2.000000      48.000000
25%         0.000000       27.000000        6.000000     162.750000
50%         0.000000       70.000000        7.000000     255.000000
75%         6.000000      140.000000       10.000000     436.000000
max      1436.000000      349.000000       14.000000    1231.000000

In [ ]:
zero_stock = (inventory['on_hand_units'] == 0).sum()
total_inventory = len(inventory)

print("Zero-stock records:", zero_stock)
print("Total inventory records:", total_inventory)
print("Zero-stock percentage:", round(zero_stock / total_inventory * 100, 2), "%")

Zero-stock records: 15971
Total inventory records: 21840
Zero-stock percentage: 73.13 %

In [ ]:
zero_stock_by_sku = (
    inventory[inventory['on_hand_units'] == 0]
    .groupby('sku_id')
    .size()
    .sort_values(ascending=False)
)

print(zero_stock_by_sku)

sku_id
SKU006    497
SKU036    495
SKU018    494
SKU025    493
SKU010    489
SKU035    484
SKU027    480
SKU007    479
SKU011    478
SKU028    473
SKU023    464
SKU030    456
SKU014    451
SKU003    443
SKU020    443
SKU005    430
SKU012    420
SKU040    419
SKU002    417
SKU001    414
SKU015    414
SKU024    409
SKU013    396
SKU009    390
SKU037    386
SKU021    383
SKU026    355
SKU031    352
SKU017    352
SKU029    338
SKU004    336
SKU032    303
SKU034    300
SKU022    299
SKU016    296
SKU019    294
SKU033    292
SKU038    289
SKU039    288
SKU008    280
dtype: int64

In [ ]:
inventory['below_reorder_point'] = (
    inventory['on_hand_units'] < inventory['reorder_point']
)

print(
    "Records below reorder point:",
    inventory['below_reorder_point'].sum()
)

print(
    "Percentage below reorder point:",
    round(
        inventory['below_reorder_point'].mean() * 100, 2
    ),
    "%"
)

Records below reorder point: 20652
Percentage below reorder point: 94.56 %

In [ ]:
zero_and_below = (
    (inventory['on_hand_units'] == 0) &
    (inventory['on_hand_units'] < inventory['reorder_point'])
).sum()

print("Zero stock & below reorder point:", zero_and_below)
print(
    "Percentage of all inventory records:",
    round(zero_and_below / len(inventory) * 100, 2),
    "%"
)

Zero stock & below reorder point: 15971
Percentage of all inventory records: 73.13 %

In [ ]:
print("Missing units_sold:", sales['units_sold'].isnull().sum())
print("Missing price:", sales['price'].isnull().sum())

print("\nRows with missing units_sold:")
print(sales[sales['units_sold'].isnull()].head(10))

print("\nRows with missing price:")
print(sales[sales['price'].isnull()].head(10))

Missing units_sold: 70
Missing price: 50

Rows with missing units_sold:
            date  sku_id  units_sold     revenue    price  promo_flag
192   2025-07-12  SKU001         NaN   359501.28  4730.28           0
202   2025-07-22  SKU001         NaN   279086.52  4730.28           0
475   2026-04-21  SKU001         NaN   227053.44  4730.28           0
574   2025-02-18  SKU002         NaN   130598.16  4664.22           0
1454  2026-01-18  SKU003         NaN    88646.04  7387.17           0
1574  2026-05-18  SKU003         NaN    73871.70  7387.17           0
2011  2026-05-30  SKU004         NaN    87072.18  1404.39           0
2016  2026-06-04  SKU004         NaN    56175.60  1404.39           0
2269  2025-08-15  SKU005         NaN  1053261.30  8102.01           0
3050  2026-04-07  SKU006         NaN    71086.29  6462.39           0

Rows with missing price:
            date  sku_id  units_sold    revenue  price  promo_flag
428   2026-03-05  SKU001        57.0  269625.96    NaN           0
881   2025-12-22  SKU002        39.0  167352.21    NaN           1
1048  2026-06-07  SKU002        19.0   88620.18    NaN           0
1480  2026-02-13  SKU003        15.0  110807.55    NaN           0
1779  2025-10-10  SKU004        44.0   56849.71    NaN           1
1991  2026-05-10  SKU004        41.0   57579.99    NaN           0
2396  2025-12-20  SKU005       127.0  946638.85    NaN           1
2647  2025-02-28  SKU006        15.0   96935.85    NaN           0
2785  2025-07-16  SKU006        15.0   96935.85    NaN           0
3500  2026-01-01  SKU007       116.0  433554.64    NaN           0

In [ ]:
sales['calculated_revenue'] = sales['units_sold'] * sales['price']

sales['revenue_difference'] = (
    sales['revenue'] - sales['calculated_revenue']
)

print(
    "Rows where revenue differs from units_sold × price:",
    (sales['revenue_difference'].abs() > 0.01).sum()
)

Rows where revenue differs from units_sold × price: 3256

In [ ]:
difference_mask = sales['revenue_difference'].abs() > 0.01

print("Total revenue differences:", difference_mask.sum())

print(
    "Promo revenue differences:",
    ((difference_mask) & (sales['promo_flag'] == 1)).sum()
)

print(
    "Non-promo revenue differences:",
    ((difference_mask) & (sales['promo_flag'] == 0)).sum()
)

Total revenue differences: 3256
Promo revenue differences: 3249
Non-promo revenue differences: 7

In [ ]:
non_promo_anomalies = sales[
    (sales['promo_flag'] == 0) &
    (sales['revenue_difference'].abs() > 0.01)
]

print(
    non_promo_anomalies[
        [
            'date',
            'sku_id',
            'units_sold',
            'price',
            'revenue',
            'calculated_revenue',
            'revenue_difference'
        ]
    ]
)

             date  sku_id  units_sold    price    revenue  calculated_revenue  \
5127   2026-01-03  SKU010       416.0  8525.33  443317.16          3546537.28
6520   2025-08-19  SKU013       136.0  7066.44  120129.48           961035.84
7640   2025-10-23  SKU015       552.0  1437.45   99184.05           793472.40
11615  2025-04-03  SKU023       680.0  4088.42  347515.70          2780125.60
13533  2026-02-01  SKU026       840.0  6741.37  707843.85          5662750.80
14550  2025-11-18  SKU028       504.0   687.38   43304.94           346439.52
18241  2026-05-24  SKU035       504.0  5788.57  364679.91          2917439.28

       revenue_difference
5127          -3103220.12
6520           -840906.36
7640           -694288.35
11615         -2432609.90
13533         -4954906.95
14550          -303134.58
18241         -2552759.37

In [ ]:
sales['sku_id_lower'] = sales['sku_id'].str.lower()

case_variations = (
    sales.groupby('sku_id_lower')['sku_id']
    .nunique()
)

print("SKU IDs with case inconsistencies:")
print(case_variations[case_variations > 1])

SKU IDs with case inconsistencies:
sku_id_lower
sku003    2
sku009    2
sku015    2
sku022    2
sku028    2
sku030    2
sku032    2
sku034    2
sku038    2
Name: sku_id, dtype: int64

In [ ]:
sales_skus = set(sales['sku_id'].str.upper())
master_skus = set(sku_master['sku_id'].str.upper())

missing_skus = sales_skus - master_skus

print("Unique SKUs in Sales:", len(sales_skus))
print("SKUs in Master:", len(master_skus))
print("Sales SKUs missing from Master:", len(missing_skus))

print("\nMissing SKUs:")
print(missing_skus)

NameError: name 'sales' is not defined

In [ ]:
import pandas as pd
import os

# Check whether the extracted folder still exists
print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
from google.colab import files
import zipfile
import os
import pandas as pd

uploaded = files.upload()

zip_name = next(iter(uploaded))

extract_path = "/content/foresight_data"

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(extract_path)

sales = pd.read_csv(f"{extract_path}/sales_daily.csv")
sku_master = pd.read_csv(f"{extract_path}/sku_master.csv")
calendar = pd.read_csv(f"{extract_path}/calendar.csv")
inventory = pd.read_csv(f"{extract_path}/inventory_snapshots.csv")

print("SUCCESS — All datasets loaded.")
print("Sales:", sales.shape)
print("SKU Master:", sku_master.shape)
print("Calendar:", calendar.shape)
print("Inventory:", inventory.shape)

Saving Project_FORESIGHT_Synthetic_Datasets.zip to Project_FORESIGHT_Synthetic_Datasets.zip
SUCCESS — All datasets loaded.
Sales: (20931, 6)
SKU Master: (40, 6)
Calendar: (546, 7)
Inventory: (21840, 6)

In [ ]:
sales_skus = set(sales['sku_id'].str.upper())
master_skus = set(sku_master['sku_id'].str.upper())

missing_skus = sales_skus - master_skus

print("Unique SKUs in Sales:", len(sales_skus))
print("SKUs in Master:", len(master_skus))
print("Sales SKUs missing from Master:", len(missing_skus))

print("\nMissing SKUs:")
print(missing_skus)

In [1]:
print(sku_master[sku_master['unit_cost'].isnull()])

NameError: name 'sku_master' is not defined

In [2]:
import os
print(os.listdir("/content"))

['.config', 'sample_data']

In [3]:
from google.colab import files
import zipfile
import pandas as pd

uploaded = files.upload()
zip_name = next(iter(uploaded))

extract_path = "/content/foresight_data"

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(extract_path)

sales = pd.read_csv(f"{extract_path}/sales_daily.csv")
sku_master = pd.read_csv(f"{extract_path}/sku_master.csv")
calendar = pd.read_csv(f"{extract_path}/calendar.csv")
inventory = pd.read_csv(f"{extract_path}/inventory_snapshots.csv")

print("SUCCESS — All datasets loaded.")
print("Sales:", sales.shape)
print("SKU Master:", sku_master.shape)
print("Calendar:", calendar.shape)
print("Inventory:", inventory.shape)

Saving Project_FORESIGHT_Synthetic_Datasets.zip to Project_FORESIGHT_Synthetic_Datasets.zip
SUCCESS — All datasets loaded.
Sales: (20931, 6)
SKU Master: (40, 6)
Calendar: (546, 7)
Inventory: (21840, 6)

In [4]:
print(sku_master[sku_master['unit_cost'].isnull()])

    sku_id    category subcategory launch_date  unit_cost  list_price
17  SKU018  Home Decor       Clock  2024-08-06        NaN      3475.7

In [5]:
duplicate_sku_ids = sku_master[
    sku_master['sku_id'].duplicated(keep=False)
]

print("Duplicate SKU IDs:", duplicate_sku_ids['sku_id'].nunique())

print("\nDuplicate SKU records:")
print(duplicate_sku_ids)

Duplicate SKU IDs: 0

Duplicate SKU records:
Empty DataFrame
Columns: [sku_id, category, subcategory, launch_date, unit_cost, list_price]
Index: []

In [1]:
print("Sales date dtype:", sales['date'].dtype)
print("SKU launch date dtype:", sku_master['launch_date'].dtype)
print("Calendar date dtype:", calendar['date'].dtype)
print("Inventory date dtype:", inventory['date'].dtype)

NameError: name 'sales' is not defined

In [2]:
import os
print(os.listdir("/content"))

['.config', 'sample_data']

In [3]:
from google.colab import files
import zipfile
import pandas as pd

uploaded = files.upload()
zip_name = next(iter(uploaded))

extract_path = "/content/foresight_data"

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(extract_path)

sales = pd.read_csv(f"{extract_path}/sales_daily.csv")
sku_master = pd.read_csv(f"{extract_path}/sku_master.csv")
calendar = pd.read_csv(f"{extract_path}/calendar.csv")
inventory = pd.read_csv(f"{extract_path}/inventory_snapshots.csv")

print("SUCCESS — All datasets loaded.")
print("Sales:", sales.shape)
print("SKU Master:", sku_master.shape)
print("Calendar:", calendar.shape)
print("Inventory:", inventory.shape)

Saving Project_FORESIGHT_Synthetic_Datasets.zip to Project_FORESIGHT_Synthetic_Datasets.zip
SUCCESS — All datasets loaded.
Sales: (20931, 6)
SKU Master: (40, 6)
Calendar: (546, 7)
Inventory: (21840, 6)

In [4]:
print("Sales date dtype:", sales['date'].dtype)
print("SKU launch date dtype:", sku_master['launch_date'].dtype)
print("Calendar date dtype:", calendar['date'].dtype)
print("Inventory date dtype:", inventory['date'].dtype)

Sales date dtype: object
SKU launch date dtype: object
Calendar date dtype: object
Inventory date dtype: object

In [5]:
for name, df, column in [
    ("Sales", sales, "date"),
    ("SKU Master", sku_master, "launch_date"),
    ("Calendar", calendar, "date"),
    ("Inventory", inventory, "date")
]:
    converted = pd.to_datetime(df[column], errors='coerce')
    invalid = converted.isna().sum()
    print(f"{name}: {invalid} invalid date values")

Sales: 0 invalid date values
SKU Master: 0 invalid date values
Calendar: 0 invalid date values
Inventory: 0 invalid date values

In [6]:
Q1 = sales['units_sold'].quantile(0.25)
Q3 = sales['units_sold'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = sales[
    (sales['units_sold'] < lower_bound) |
    (sales['units_sold'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of units_sold outliers:", len(outliers))

Q1: 34.0
Q3: 83.0
IQR: 49.0
Lower bound: -39.5
Upper bound: 156.5
Number of units_sold outliers: 124

In [7]:
print(
    sales.nlargest(
        10,
        'units_sold'
    )[
        [
            'date',
            'sku_id',
            'units_sold',
            'revenue',
            'price',
            'promo_flag'
        ]
    ]
)

             date  sku_id  units_sold     revenue    price  promo_flag
13533  2026-02-01  SKU026       840.0   707843.85  6741.37           0
11615  2025-04-03  SKU023       680.0   347515.70  4088.42           0
7640   2025-10-23  SKU015       552.0    99184.05  1437.45           0
14550  2025-11-18  SKU028       504.0    43304.94   687.38           0
18241  2026-05-24  SKU035       504.0   364679.91  5788.57           0
5127   2026-01-03  SKU010       416.0   443317.16  8525.33           0
13671  2026-06-19  SKU026       233.0  1445080.07  6741.37           1
16007  2025-11-23  SKU031       232.0    78861.81  2955.84           1
5820   2026-06-12  SKU011       226.0   660746.89  3177.89           1
4208   2026-06-12  SKU008       223.0  1484829.09  7237.42           1

In [8]:
Q1 = sales['price'].quantile(0.25)
Q3 = sales['price'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

price_outliers = sales[
    (sales['price'] < lower_bound) |
    (sales['price'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of price outliers:", len(price_outliers))

Q1: 1844.52
Q3: 5788.57
IQR: 3944.0499999999997
Lower bound: -4071.555
Upper bound: 11704.645
Number of price outliers: 0

In [9]:
Q1 = sales['revenue'].quantile(0.25)
Q3 = sales['revenue'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

revenue_outliers = sales[
    (sales['revenue'] < lower_bound) |
    (sales['revenue'] > upper_bound)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)
print("Number of revenue outliers:", len(revenue_outliers))

Q1: 89121.9
Q3: 327322.67
IQR: 238200.77
Lower bound: -268179.255
Upper bound: 684623.825
Number of revenue outliers: 966

In [10]:
print(sales['promo_flag'].value_counts(dropna=False))

promo_flag
0    17657
1     3274
Name: count, dtype: int64

In [11]:
print("===== LEAD TIME =====")
print(inventory['lead_time_days'].describe())

print("\n===== REORDER POINT =====")
print(inventory['reorder_point'].describe())

print("\n===== INVENTORY MISSING VALUES =====")
print(inventory[['on_hand_units', 'lead_time_days']].isnull().sum())

print("\n===== CALENDAR PROMOTION FLAG =====")
print(calendar['promo_flag'].value_counts(dropna=False))

print("\n===== CALENDAR PROMO EVENTS =====")
print(calendar['promo_event'].value_counts(dropna=False))

print("\n===== SKU MASTER CATEGORIES =====")
print(sku_master['category'].value_counts())

print("\n===== SKU MASTER SUBCATEGORIES =====")
print(sku_master['subcategory'].value_counts())

===== LEAD TIME =====
count    21800.000000
mean         7.800046
std          3.743063
min          2.000000
25%          6.000000
50%          7.000000
75%         10.000000
max         14.000000
Name: lead_time_days, dtype: float64

===== REORDER POINT =====
count    21840.000000
mean       337.625000
std        258.342293
min         48.000000
25%        162.750000
50%        255.000000
75%        436.000000
max       1231.000000
Name: reorder_point, dtype: float64

===== INVENTORY MISSING VALUES =====
on_hand_units     40
lead_time_days    40
dtype: int64

===== CALENDAR PROMOTION FLAG =====
promo_flag
0    461
1     85
Name: count, dtype: int64

===== CALENDAR PROMO EVENTS =====
promo_event
NaN              461
Summer Sale       22
Spring Sale       19
Year End Sale     17
Black Friday      11
Festive Sale      10
New Year Sale      6
Name: count, dtype: int64

===== SKU MASTER CATEGORIES =====
category
Furniture           10
Home Decor          10
Small Appliances    10
Office              10
Name: count, dtype: int64

===== SKU MASTER SUBCATEGORIES =====
subcategory
Chair           10
Toaster         10
Organizer       10
Clock            9
 home decor      1
Name: count, dtype: int64

In [12]:
# Make a copy so the original raw data remains unchanged
sales_clean = sales.copy()
sku_master_clean = sku_master.copy()
calendar_clean = calendar.copy()
inventory_clean = inventory.copy()

# 1. Convert date columns to datetime
sales_clean['date'] = pd.to_datetime(sales_clean['date'])
sku_master_clean['launch_date'] = pd.to_datetime(sku_master_clean['launch_date'])
calendar_clean['date'] = pd.to_datetime(calendar_clean['date'])
inventory_clean['date'] = pd.to_datetime(inventory_clean['date'])

# 2. Standardize SKU IDs to uppercase
sales_clean['sku_id'] = sales_clean['sku_id'].str.upper()
sku_master_clean['sku_id'] = sku_master_clean['sku_id'].str.upper()
inventory_clean['sku_id'] = inventory_clean['sku_id'].str.upper()

# 3. Remove accidental leading/trailing spaces from text fields
sku_master_clean['category'] = sku_master_clean['category'].str.strip()
sku_master_clean['subcategory'] = sku_master_clean['subcategory'].str.strip()

print("Cleaning transformations completed.")
print()
print("Sales date dtype:", sales_clean['date'].dtype)
print("SKU launch date dtype:", sku_master_clean['launch_date'].dtype)
print("Calendar date dtype:", calendar_clean['date'].dtype)
print("Inventory date dtype:", inventory_clean['date'].dtype)

print("\nUnique Sales SKUs:", sales_clean['sku_id'].nunique())
print("Unique Master SKUs:", sku_master_clean['sku_id'].nunique())
print("Unique Inventory SKUs:", inventory_clean['sku_id'].nunique())

Cleaning transformations completed.

Sales date dtype: datetime64[ns]
SKU launch date dtype: datetime64[ns]
Calendar date dtype: datetime64[ns]
Inventory date dtype: datetime64[ns]

Unique Sales SKUs: 40
Unique Master SKUs: 40
Unique Inventory SKUs: 40

In [13]:
duplicates_before = sales_clean.duplicated().sum()

sales_clean = sales_clean.drop_duplicates().reset_index(drop=True)

duplicates_after = sales_clean.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates removed:", duplicates_before - duplicates_after)
print("Duplicates after cleaning:", duplicates_after)
print("Sales rows after cleaning:", len(sales_clean))

Duplicates before cleaning: 25
Duplicates removed: 25
Duplicates after cleaning: 0
Sales rows after cleaning: 20906

In [14]:
duplicates_before = sales_clean.duplicated().sum()

sales_clean = sales_clean.drop_duplicates().reset_index(drop=True)

duplicates_after = sales_clean.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates removed:", duplicates_before - duplicates_after)
print("Duplicates after cleaning:", duplicates_after)
print("Sales rows after cleaning:", len(sales_clean))

Duplicates before cleaning: 0
Duplicates removed: 0
Duplicates after cleaning: 0
Sales rows after cleaning: 20906

In [15]:
missing_units = sales_clean[sales_clean['units_sold'].isna()].copy()

missing_units['calculated_units'] = (
    missing_units['revenue'] / missing_units['price']
)

print(missing_units[
    ['date', 'sku_id', 'units_sold', 'revenue', 'price', 'calculated_units']
].head(10))

           date  sku_id  units_sold     revenue    price  calculated_units
192  2025-07-12  SKU001         NaN   359501.28  4730.28              76.0
202  2025-07-22  SKU001         NaN   279086.52  4730.28              59.0
475  2026-04-21  SKU001         NaN   227053.44  4730.28              48.0
574  2025-02-18  SKU002         NaN   130598.16  4664.22              28.0
1454 2026-01-18  SKU003         NaN    88646.04  7387.17              12.0
1574 2026-05-18  SKU003         NaN    73871.70  7387.17              10.0
2011 2026-05-30  SKU004         NaN    87072.18  1404.39              62.0
2016 2026-06-04  SKU004         NaN    56175.60  1404.39              40.0
2269 2025-08-15  SKU005         NaN  1053261.30  8102.01             130.0
3050 2026-04-07  SKU006         NaN    71086.29  6462.39              11.0

In [16]:
missing_units = sales_clean[sales_clean['units_sold'].isna()].copy()

missing_units['calculated_units'] = (
    missing_units['revenue'] / missing_units['price']
)

# Check whether calculated values are effectively whole numbers
non_integer_units = missing_units[
    (missing_units['calculated_units'] -
     missing_units['calculated_units'].round()).abs() > 0.01
]

print("Missing units records:", len(missing_units))
print("Calculated units:", missing_units['calculated_units'].notna().sum())
print("Non-integer calculated units:", len(non_integer_units))

print("\nCalculated units summary:")
print(missing_units['calculated_units'].describe())

Missing units records: 70
Calculated units: 70
Non-integer calculated units: 15

Calculated units summary:
count     70.000000
mean      60.629714
std       33.372575
min        7.000000
25%       32.500000
50%       60.500000
75%       87.750000
max      136.160000
Name: calculated_units, dtype: float64

In [17]:
non_integer_units = missing_units[
    (missing_units['calculated_units'] -
     missing_units['calculated_units'].round()).abs() > 0.01
]

print(
    non_integer_units[
        [
            'date',
            'sku_id',
            'units_sold',
            'revenue',
            'price',
            'promo_flag',
            'calculated_units'
        ]
    ]
)

            date  sku_id  units_sold    revenue    price  promo_flag  \
3144  2025-01-10  SKU007         NaN  443571.25  3737.54           1
4581  2025-12-21  SKU009         NaN   74676.83  4272.13           1
5089  2025-11-26  SKU010         NaN  635307.59  8525.33           1
7427  2025-03-24  SKU015         NaN   93894.23  1437.45           1
10511 2025-03-22  SKU021         NaN   65724.06   637.85           1
10597 2025-06-16  SKU021         NaN   53987.62   637.85           1
12321 2025-10-04  SKU024         NaN   63726.65  1259.42           1
12485 2026-03-17  SKU024         NaN   69519.98  1259.42           1
12489 2026-03-21  SKU024         NaN   92693.31  1259.42           1
12868 2025-10-05  SKU025         NaN  395639.11  4175.17           1
13305 2025-06-18  SKU026         NaN  917904.94  6741.37           1
14398 2025-06-19  SKU028         NaN   61341.79   687.38           1
16128 2026-03-24  SKU031         NaN   54387.46  2955.84           1
16506 2025-10-07  SKU032         NaN  153220.57  5551.47           1
19716 2026-03-25  SKU038         NaN  351763.18  3010.64           1

       calculated_units
3144         118.680001
4581          17.479999
5089          74.520000
7427          65.319997
10511        103.039994
10597         84.639994
12321         50.599998
12485         55.199997
12489         73.599998
12868         94.760000
13305        136.160000
14398         89.239998
16128         18.400001
16506         27.600000
19716        116.840001

In [18]:
whole_unit_candidates = missing_units[
    (missing_units['calculated_units'] -
     missing_units['calculated_units'].round()).abs() <= 0.01
].copy()

print("Whole-unit candidates:", len(whole_unit_candidates))
print(
    whole_unit_candidates[
        ['date', 'sku_id', 'revenue', 'price',
         'promo_flag', 'calculated_units']
    ].head(20)
)

Whole-unit candidates: 55
           date  sku_id     revenue    price  promo_flag  calculated_units
192  2025-07-12  SKU001   359501.28  4730.28           0              76.0
202  2025-07-22  SKU001   279086.52  4730.28           0              59.0
475  2026-04-21  SKU001   227053.44  4730.28           0              48.0
574  2025-02-18  SKU002   130598.16  4664.22           0              28.0
1454 2026-01-18  SKU003    88646.04  7387.17           0              12.0
1574 2026-05-18  SKU003    73871.70  7387.17           0              10.0
2011 2026-05-30  SKU004    87072.18  1404.39           0              62.0
2016 2026-06-04  SKU004    56175.60  1404.39           0              40.0
2269 2025-08-15  SKU005  1053261.30  8102.01           0             130.0
3050 2026-04-07  SKU006    71086.29  6462.39           0              11.0
3154 2025-01-20  SKU007   220514.86  3737.54           0              59.0
3200 2025-03-07  SKU007   388704.16  3737.54           0             104.0
3244 2025-04-20  SKU007   175664.38  3737.54           0              47.0
3255 2025-05-01  SKU007   295265.66  3737.54           0              79.0
3503 2026-01-04  SKU007   377491.54  3737.54           0             101.0
3673 2026-06-23  SKU007   381229.08  3737.54           0             102.0
3707 2025-01-27  SKU008   578993.60  7237.42           0              80.0
4260 2025-02-03  SKU009    46993.43  4272.13           0              11.0
4481 2025-09-12  SKU009    76898.34  4272.13           0              18.0
5003 2025-09-01  SKU010   298386.55  8525.33           0              35.0

In [19]:
# Fill only the 55 confirmed whole-unit values
sales_clean.loc[
    whole_unit_candidates.index,
    'units_sold'
] = whole_unit_candidates['calculated_units'].round()

print(
    "Remaining missing units_sold:",
    sales_clean['units_sold'].isna().sum()
)

print(
    "Units_sold values filled:",
    70 - sales_clean['units_sold'].isna().sum()
)

Remaining missing units_sold: 15
Units_sold values filled: 55

In [20]:
remaining_missing_units = sales_clean[
    sales_clean['units_sold'].isna()
].copy()

print("Remaining missing units:", len(remaining_missing_units))

print(
    remaining_missing_units[
        [
            'date',
            'sku_id',
            'revenue',
            'price',
            'promo_flag'
        ]
    ]
)

Remaining missing units: 15
            date  sku_id    revenue    price  promo_flag
3144  2025-01-10  SKU007  443571.25  3737.54           1
4581  2025-12-21  SKU009   74676.83  4272.13           1
5089  2025-11-26  SKU010  635307.59  8525.33           1
7427  2025-03-24  SKU015   93894.23  1437.45           1
10511 2025-03-22  SKU021   65724.06   637.85           1
10597 2025-06-16  SKU021   53987.62   637.85           1
12321 2025-10-04  SKU024   63726.65  1259.42           1
12485 2026-03-17  SKU024   69519.98  1259.42           1
12489 2026-03-21  SKU024   92693.31  1259.42           1
12868 2025-10-05  SKU025  395639.11  4175.17           1
13305 2025-06-18  SKU026  917904.94  6741.37           1
14398 2025-06-19  SKU028   61341.79   687.38           1
16128 2026-03-24  SKU031   54387.46  2955.84           1
16506 2025-10-07  SKU032  153220.57  5551.47           1
19716 2026-03-25  SKU038  351763.18  3010.64           1

In [21]:
missing_price = sales_clean[
    sales_clean['price'].isna()
].copy()

missing_price['calculated_price'] = (
    missing_price['revenue'] / missing_price['units_sold']
)

print("Missing price records:", len(missing_price))

print(
    missing_price[
        [
            'date',
            'sku_id',
            'units_sold',
            'revenue',
            'price',
            'promo_flag',
            'calculated_price'
        ]
    ].head(20)
)

Missing price records: 50
           date  sku_id  units_sold    revenue  price  promo_flag  \
428  2026-03-05  SKU001        57.0  269625.96    NaN           0
881  2025-12-22  SKU002        39.0  167352.21    NaN           1
1048 2026-06-07  SKU002        19.0   88620.18    NaN           0
1480 2026-02-13  SKU003        15.0  110807.55    NaN           0
1779 2025-10-10  SKU004        44.0   56849.71    NaN           1
1991 2026-05-10  SKU004        41.0   57579.99    NaN           0
2396 2025-12-20  SKU005       127.0  946638.85    NaN           1
2647 2025-02-28  SKU006        15.0   96935.85    NaN           0
2785 2025-07-16  SKU006        15.0   96935.85    NaN           0
3500 2026-01-01  SKU007       116.0  433554.64    NaN           0
3582 2026-03-24  SKU007       101.0  347292.22    NaN           1
3609 2026-04-20  SKU007        61.0  227989.94    NaN           0
3703 2025-01-23  SKU008        68.0  492144.56    NaN           0
3889 2025-07-28  SKU008        86.0  622418.12    NaN           0
4660 2026-03-10  SKU009        10.0   42721.30    NaN           0
4903 2025-05-24  SKU010        56.0  477418.48    NaN           0
5255 2026-05-11  SKU010        59.0  502994.47    NaN           0
6859 2025-01-30  SKU014        67.0  215144.37    NaN           0
7070 2025-08-29  SKU014       114.0  366066.54    NaN           0
7233 2026-02-08  SKU014       117.0  375699.87    NaN           0

      calculated_price
428        4730.280000
881        4291.082308
1048       4664.220000
1480       7387.170000
1779       1292.038864
1991       1404.390000
2396       7453.849213
2647       6462.390000
2785       6462.390000
3500       3737.540000
3582       3438.536832
3609       3737.540000
3703       7237.420000
3889       7237.420000
4660       4272.130000
4903       8525.330000
5255       8525.330000
6859       3211.110000
7070       3211.110000
7233       3211.110000

In [23]:
# Compare calculated price with the SKU Master's list price

missing_price_check = missing_price.merge(
    sku_master_clean[['sku_id', 'list_price']],
    on='sku_id',
    how='left'
)

missing_price_check['price_difference'] = (
    missing_price_check['calculated_price']
    - missing_price_check['list_price']
)

# Non-promo records where calculated price matches list price
nonpromo_price_candidates = missing_price_check[
    (missing_price_check['promo_flag'] == 0) &
    (missing_price_check['price_difference'].abs() <= 0.01)
]

print("Total missing prices:", len(missing_price_check))
print("Non-promo exact price candidates:", len(nonpromo_price_candidates))
print("Promotional missing prices:",
      (missing_price_check['promo_flag'] == 1).sum())

print("\nNon-promo candidates:")
print(
    nonpromo_price_candidates[
        [
            'date',
            'sku_id',
            'units_sold',
            'revenue',
            'calculated_price',
            'list_price',
            'promo_flag'
        ]
    ].head(20)
)

Total missing prices: 50
Non-promo exact price candidates: 40
Promotional missing prices: 10

Non-promo candidates:
         date  sku_id  units_sold    revenue  calculated_price  list_price  \
0  2026-03-05  SKU001        57.0  269625.96           4730.28     4730.28
2  2026-06-07  SKU002        19.0   88620.18           4664.22     4664.22
3  2026-02-13  SKU003        15.0  110807.55           7387.17     7387.17
5  2026-05-10  SKU004        41.0   57579.99           1404.39     1404.39
7  2025-02-28  SKU006        15.0   96935.85           6462.39     6462.39
8  2025-07-16  SKU006        15.0   96935.85           6462.39     6462.39
9  2026-01-01  SKU007       116.0  433554.64           3737.54     3737.54
11 2026-04-20  SKU007        61.0  227989.94           3737.54     3737.54
12 2025-01-23  SKU008        68.0  492144.56           7237.42     7237.42
13 2025-07-28  SKU008        86.0  622418.12           7237.42     7237.42
14 2026-03-10  SKU009        10.0   42721.30           4272.13     4272.13
15 2025-05-24  SKU010        56.0  477418.48           8525.33     8525.33
16 2026-05-11  SKU010        59.0  502994.47           8525.33     8525.33
17 2025-01-30  SKU014        67.0  215144.37           3211.11     3211.11
18 2025-08-29  SKU014       114.0  366066.54           3211.11     3211.11
19 2026-02-08  SKU014       117.0  375699.87           3211.11     3211.11
20 2025-12-11  SKU015        75.0  107808.75           1437.45     1437.45
21 2025-03-07  SKU016        88.0  212617.68           2416.11     2416.11
23 2026-04-04  SKU017        61.0  463192.52           7593.32     7593.32
24 2025-07-14  SKU018        63.0  218969.10           3475.70     3475.70

    promo_flag
0            0
2            0
3            0
5            0
7            0
8            0
9            0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
23           0
24           0

In [24]:
# Fill only the 40 confirmed non-promo price values
sales_clean.loc[
    nonpromo_price_candidates.index,
    'price'
] = nonpromo_price_candidates['list_price'].values

print("Remaining missing prices:",
      sales_clean['price'].isna().sum())

print("Prices filled:",
      50 - sales_clean['price'].isna().sum())

Remaining missing prices: 50
Prices filled: 0

In [25]:
# Get the original sales indices for the 40 confirmed candidates
nonpromo_price_indices = missing_price[
    missing_price['promo_flag'] == 0
].index

# Fill price using the calculated price
sales_clean.loc[
    nonpromo_price_indices,
    'price'
] = (
    sales_clean.loc[
        nonpromo_price_indices,
        'revenue'
    ] /
    sales_clean.loc[
        nonpromo_price_indices,
        'units_sold'
    ]
)

print("Remaining missing prices:",
      sales_clean['price'].isna().sum())

print("Prices filled:",
      50 - sales_clean['price'].isna().sum())

Remaining missing prices: 10
Prices filled: 40

In [26]:
remaining_missing_price = sales_clean[
    sales_clean['price'].isna()
].copy()

print("Remaining missing prices:", len(remaining_missing_price))

print(
    remaining_missing_price[
        [
            'date',
            'sku_id',
            'units_sold',
            'revenue',
            'promo_flag'
        ]
    ]
)

Remaining missing prices: 10
            date  sku_id  units_sold    revenue  promo_flag
881   2025-12-22  SKU002        39.0  167352.21           1
1779  2025-10-10  SKU004        44.0   56849.71           1
2396  2025-12-20  SKU005       127.0  946638.85           1
3582  2026-03-24  SKU007       101.0  347292.22           1
8607  2025-10-02  SKU017        76.0  530924.93           1
9239  2025-12-27  SKU018       128.0  409298.43           1
14124 2026-03-18  SKU027        49.0  190316.04           1
15723 2026-06-12  SKU030        79.0  130474.41           1
16590 2025-12-30  SKU032        31.0  158327.92           1
20638 2025-10-06  SKU040        52.0   88241.84           1

In [27]:
remaining_missing_price['calculated_price'] = (
    remaining_missing_price['revenue'] /
    remaining_missing_price['units_sold']
)

print(
    remaining_missing_price[
        [
            'date',
            'sku_id',
            'units_sold',
            'revenue',
            'calculated_price'
        ]
    ]
)

            date  sku_id  units_sold    revenue  calculated_price
881   2025-12-22  SKU002        39.0  167352.21       4291.082308
1779  2025-10-10  SKU004        44.0   56849.71       1292.038864
2396  2025-12-20  SKU005       127.0  946638.85       7453.849213
3582  2026-03-24  SKU007       101.0  347292.22       3438.536832
8607  2025-10-02  SKU017        76.0  530924.93       6985.854342
9239  2025-12-27  SKU018       128.0  409298.43       3197.643984
14124 2026-03-18  SKU027        49.0  190316.04       3884.000816
15723 2026-06-12  SKU030        79.0  130474.41       1651.574810
16590 2025-12-30  SKU032        31.0  158327.92       5107.352258
20638 2025-10-06  SKU040        52.0   88241.84       1696.958462

In [28]:
print(sku_master_clean[
    sku_master_clean['unit_cost'].isna()
])

    sku_id    category subcategory launch_date  unit_cost  list_price
17  SKU018  Home Decor       Clock  2024-08-06        NaN      3475.7

In [29]:
print("SKU018:")
print(
    sku_master_clean[
        sku_master_clean['sku_id'] == 'SKU018'
    ]
)

print("\nSame category:")
print(
    sku_master_clean[
        sku_master_clean['category'] == 'Home Decor'
    ][
        ['sku_id', 'subcategory', 'unit_cost', 'list_price']
    ]
)

print("\nSame subcategory:")
print(
    sku_master_clean[
        sku_master_clean['subcategory'] == 'Clock'
    ][
        ['sku_id', 'category', 'unit_cost', 'list_price']
    ]
)

SKU018:
    sku_id    category subcategory launch_date  unit_cost  list_price
17  SKU018  Home Decor       Clock  2024-08-06        NaN      3475.7

Same category:
    sku_id subcategory  unit_cost  list_price
1   SKU002       Clock    3577.63     4664.22
5   SKU006  home decor    4166.98     6462.39
9   SKU010       Clock    4497.67     8525.33
13  SKU014       Clock    2041.16     3211.11
17  SKU018       Clock        NaN     3475.70
21  SKU022       Clock    3424.80     6190.98
25  SKU026       Clock    3895.49     6741.37
29  SKU030       Clock    1399.52     1795.19
33  SKU034       Clock    1084.77     1369.57
37  SKU038       Clock    2090.80     3010.64

Same subcategory:
    sku_id    category  unit_cost  list_price
1   SKU002  Home Decor    3577.63     4664.22
9   SKU010  Home Decor    4497.67     8525.33
13  SKU014  Home Decor    2041.16     3211.11
17  SKU018  Home Decor        NaN     3475.70
21  SKU022  Home Decor    3424.80     6190.98
25  SKU026  Home Decor    3895.49     6741.37
29  SKU030  Home Decor    1399.52     1795.19
33  SKU034  Home Decor    1084.77     1369.57
37  SKU038  Home Decor    2090.80     3010.64

In [30]:
print(
    inventory_clean[
        inventory_clean['on_hand_units'].isna()
    ][
        [
            'date',
            'sku_id',
            'on_hand_units',
            'on_order_units',
            'lead_time_days',
            'reorder_point'
        ]
    ].head(20)
)

            date  sku_id  on_hand_units  on_order_units  lead_time_days  \
338   2025-12-05  SKU001            NaN              69             6.0
462   2026-04-08  SKU001            NaN              33             6.0
501   2026-05-17  SKU001            NaN             107             6.0
591   2025-02-15  SKU002            NaN              13             7.0
1195  2025-04-14  SKU003            NaN               0             7.0
1384  2025-10-20  SKU003            NaN              36             7.0
1427  2025-12-02  SKU003            NaN              31             7.0
1806  2025-06-18  SKU004            NaN              77            10.0
2449  2025-09-23  SKU005            NaN             168             7.0
2454  2025-09-28  SKU005            NaN               0             7.0
2941  2025-07-31  SKU006            NaN              16            14.0
3334  2025-02-28  SKU007            NaN             132             8.0
4339  2026-06-02  SKU008            NaN             215             2.0
5474  2025-01-15  SKU011            NaN             102            14.0
6381  2026-01-11  SKU012            NaN              31             6.0
6448  2026-03-19  SKU012            NaN              75             6.0
8311  2025-05-02  SKU016            NaN             213             3.0
8429  2025-08-28  SKU016            NaN             186             3.0
8678  2026-05-04  SKU016            NaN             159             3.0
10180 2025-12-19  SKU019            NaN             110             3.0

       reorder_point
338              255
462              255
501              255
591              107
1195              48
1384              48
1427              48
1806             360
2449             460
2454             460
2941             129
3334             417
4339             209
5474            1231
6381             237
6448             237
8311             255
8429             255
8678             255
10180             94

In [31]:
# Look at the rows immediately before and after each missing on-hand value
missing_inventory = inventory_clean[
    inventory_clean['on_hand_units'].isna()
].copy()

inventory_sorted = inventory_clean.sort_values(
    ['sku_id', 'date']
).copy()

for idx in missing_inventory.index[:10]:
    sku = inventory_clean.loc[idx, 'sku_id']
    date = inventory_clean.loc[idx, 'date']

    nearby = inventory_sorted[
        (inventory_sorted['sku_id'] == sku) &
        (inventory_sorted['date'].between(
            date - pd.Timedelta(days=2),
            date + pd.Timedelta(days=2)
        ))
    ][
        [
            'date',
            'sku_id',
            'on_hand_units',
            'on_order_units',
            'lead_time_days',
            'reorder_point'
        ]
    ]

    print(f"\nMissing record: {sku} | {date.date()}")
    print(nearby.to_string(index=False))

Missing record: SKU001 | 2025-12-05
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-12-03 SKU001            0.0              85             6.0            255
2025-12-04 SKU001            0.0              26             6.0            255
2025-12-05 SKU001            NaN              69             6.0            255
2025-12-06 SKU001           11.0               0             6.0            255
2025-12-07 SKU001            0.0              50             6.0            255

Missing record: SKU001 | 2026-04-08
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2026-04-06 SKU001           29.0               0             6.0            255
2026-04-07 SKU001            0.0             153             6.0            255
2026-04-08 SKU001            NaN              33             6.0            255
2026-04-09 SKU001            0.0             100             6.0            255
2026-04-10 SKU001            0.0             128             6.0            255

Missing record: SKU001 | 2026-05-17
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2026-05-15 SKU001            0.0             142             6.0            255
2026-05-16 SKU001            0.0             136             6.0            255
2026-05-17 SKU001            NaN             107             6.0            255
2026-05-18 SKU001           55.0               0             6.0            255
2026-05-19 SKU001            1.0             100             6.0            255

Missing record: SKU002 | 2025-02-15
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-02-13 SKU002            0.0              22             7.0            107
2025-02-14 SKU002            6.0               0             7.0            107
2025-02-15 SKU002            NaN              13             7.0            107
2025-02-16 SKU002            0.0              34             7.0            107
2025-02-17 SKU002            0.0              15             7.0            107

Missing record: SKU003 | 2025-04-14
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-04-12 SKU003            0.0              31             7.0             48
2025-04-13 SKU003            0.0              29             7.0             48
2025-04-14 SKU003            NaN               0             7.0             48
2025-04-15 SKU003            0.0              33             7.0             48
2025-04-16 SKU003            0.0              20             7.0             48

Missing record: SKU003 | 2025-10-20
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-10-18 SKU003            0.0              26             7.0             48
2025-10-19 SKU003            0.0              14             7.0             48
2025-10-20 SKU003            NaN              36             7.0             48
2025-10-21 SKU003           13.0               0             7.0             48
2025-10-22 SKU003            8.0              14             7.0             48

Missing record: SKU003 | 2025-12-02
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-11-30 SKU003            0.0               6             7.0             48
2025-12-01 SKU003            0.0              22             7.0             48
2025-12-02 SKU003            NaN              31             7.0             48
2025-12-03 SKU003            0.0               6             7.0             48
2025-12-04 SKU003            0.0               6             7.0             48

Missing record: SKU004 | 2025-06-18
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-06-16 SKU004            0.0              61            10.0            360
2025-06-17 SKU004            0.0              82            10.0            360
2025-06-18 SKU004            NaN              77            10.0            360
2025-06-19 SKU004            0.0              37            10.0            360
2025-06-20 SKU004           50.0               0            10.0            360

Missing record: SKU005 | 2025-09-23
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-09-21 SKU005           35.0               0             7.0            460
2025-09-22 SKU005            0.0              95             7.0            460
2025-09-23 SKU005            NaN             168             7.0            460
2025-09-24 SKU005            0.0             193             7.0            460
2025-09-25 SKU005            0.0             282             7.0            460

Missing record: SKU005 | 2025-09-28
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-09-26 SKU005            0.0             134             7.0            460
2025-09-27 SKU005            0.0             271             7.0            460
2025-09-28 SKU005            NaN               0             7.0            460
2025-09-29 SKU005           75.0             213             7.0            460
2025-09-30 SKU005           12.0              79             7.0            460

In [32]:
# Look at the rows immediately before and after each missing on-hand value
missing_inventory = inventory_clean[
    inventory_clean['on_hand_units'].isna()
].copy()

inventory_sorted = inventory_clean.sort_values(
    ['sku_id', 'date']
).copy()

for idx in missing_inventory.index[:10]:
    sku = inventory_clean.loc[idx, 'sku_id']
    date = inventory_clean.loc[idx, 'date']

    nearby = inventory_sorted[
        (inventory_sorted['sku_id'] == sku) &
        (inventory_sorted['date'].between(
            date - pd.Timedelta(days=2),
            date + pd.Timedelta(days=2)
        ))
    ][
        [
            'date',
            'sku_id',
            'on_hand_units',
            'on_order_units',
            'lead_time_days',
            'reorder_point'
        ]
    ]

    print(f"\nMissing record: {sku} | {date.date()}")
    print(nearby.to_string(index=False))

Missing record: SKU001 | 2025-12-05
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-12-03 SKU001            0.0              85             6.0            255
2025-12-04 SKU001            0.0              26             6.0            255
2025-12-05 SKU001            NaN              69             6.0            255
2025-12-06 SKU001           11.0               0             6.0            255
2025-12-07 SKU001            0.0              50             6.0            255

Missing record: SKU001 | 2026-04-08
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2026-04-06 SKU001           29.0               0             6.0            255
2026-04-07 SKU001            0.0             153             6.0            255
2026-04-08 SKU001            NaN              33             6.0            255
2026-04-09 SKU001            0.0             100             6.0            255
2026-04-10 SKU001            0.0             128             6.0            255

Missing record: SKU001 | 2026-05-17
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2026-05-15 SKU001            0.0             142             6.0            255
2026-05-16 SKU001            0.0             136             6.0            255
2026-05-17 SKU001            NaN             107             6.0            255
2026-05-18 SKU001           55.0               0             6.0            255
2026-05-19 SKU001            1.0             100             6.0            255

Missing record: SKU002 | 2025-02-15
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-02-13 SKU002            0.0              22             7.0            107
2025-02-14 SKU002            6.0               0             7.0            107
2025-02-15 SKU002            NaN              13             7.0            107
2025-02-16 SKU002            0.0              34             7.0            107
2025-02-17 SKU002            0.0              15             7.0            107

Missing record: SKU003 | 2025-04-14
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-04-12 SKU003            0.0              31             7.0             48
2025-04-13 SKU003            0.0              29             7.0             48
2025-04-14 SKU003            NaN               0             7.0             48
2025-04-15 SKU003            0.0              33             7.0             48
2025-04-16 SKU003            0.0              20             7.0             48

Missing record: SKU003 | 2025-10-20
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-10-18 SKU003            0.0              26             7.0             48
2025-10-19 SKU003            0.0              14             7.0             48
2025-10-20 SKU003            NaN              36             7.0             48
2025-10-21 SKU003           13.0               0             7.0             48
2025-10-22 SKU003            8.0              14             7.0             48

Missing record: SKU003 | 2025-12-02
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-11-30 SKU003            0.0               6             7.0             48
2025-12-01 SKU003            0.0              22             7.0             48
2025-12-02 SKU003            NaN              31             7.0             48
2025-12-03 SKU003            0.0               6             7.0             48
2025-12-04 SKU003            0.0               6             7.0             48

Missing record: SKU004 | 2025-06-18
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-06-16 SKU004            0.0              61            10.0            360
2025-06-17 SKU004            0.0              82            10.0            360
2025-06-18 SKU004            NaN              77            10.0            360
2025-06-19 SKU004            0.0              37            10.0            360
2025-06-20 SKU004           50.0               0            10.0            360

Missing record: SKU005 | 2025-09-23
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-09-21 SKU005           35.0               0             7.0            460
2025-09-22 SKU005            0.0              95             7.0            460
2025-09-23 SKU005            NaN             168             7.0            460
2025-09-24 SKU005            0.0             193             7.0            460
2025-09-25 SKU005            0.0             282             7.0            460

Missing record: SKU005 | 2025-09-28
      date sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
2025-09-26 SKU005            0.0             134             7.0            460
2025-09-27 SKU005            0.0             271             7.0            460
2025-09-28 SKU005            NaN               0             7.0            460
2025-09-29 SKU005           75.0             213             7.0            460
2025-09-30 SKU005           12.0              79             7.0            460

In [33]:
# Check the number of unique non-missing lead times for each SKU
lead_time_check = (
    inventory_clean
    .dropna(subset=['lead_time_days'])
    .groupby('sku_id')['lead_time_days']
    .nunique()
    .sort_values(ascending=False)
)

print("SKUs with more than one lead-time value:")
print(lead_time_check[lead_time_check > 1])

print("\nNumber of SKUs with consistent lead time:")
print((lead_time_check == 1).sum())

print("Total SKUs with observed lead time:")
print(len(lead_time_check))

SKUs with more than one lead-time value:
Series([], Name: lead_time_days, dtype: int64)

Number of SKUs with consistent lead time:
40
Total SKUs with observed lead time:
40

In [34]:
# Calculate the consistent lead time for each SKU
sku_lead_time = (
    inventory_clean
    .dropna(subset=['lead_time_days'])
    .groupby('sku_id')['lead_time_days']
    .first()
)

# Fill missing lead times using the SKU-specific value
missing_lead_time_mask = inventory_clean['lead_time_days'].isna()

inventory_clean.loc[
    missing_lead_time_mask,
    'lead_time_days'
] = (
    inventory_clean.loc[
        missing_lead_time_mask,
        'sku_id'
    ].map(sku_lead_time)
)

print(
    "Remaining missing lead_time_days:",
    inventory_clean['lead_time_days'].isna().sum()
)

print(
    "Lead-time values filled:",
    40 - inventory_clean['lead_time_days'].isna().sum()
)

Remaining missing lead_time_days: 0
Lead-time values filled: 40

In [35]:
print(
    inventory_clean[
        inventory_clean['on_hand_units'] < 0
    ]
)

           date  sku_id  on_hand_units  on_order_units  lead_time_days  \
1234 2025-05-23  SKU003          -25.0              18             7.0

      reorder_point
1234             48

In [36]:
sales_clean['calculated_revenue'] = (
    sales_clean['units_sold'] * sales_clean['price']
)

sales_clean['revenue_difference'] = (
    sales_clean['revenue'] -
    sales_clean['calculated_revenue']
)

valid_comparison = sales_clean[
    sales_clean['units_sold'].notna() &
    sales_clean['price'].notna()
]

inconsistencies = valid_comparison[
    valid_comparison['revenue_difference'].abs() > 0.01
]

print("Rows available for revenue validation:", len(valid_comparison))
print("Revenue inconsistencies:", len(inconsistencies))

print("\nBy promotion status:")
print(
    inconsistencies['promo_flag']
    .value_counts()
)

Rows available for revenue validation: 20881
Revenue inconsistencies: 3288

By promotion status:
promo_flag
1    3247
0      41
Name: count, dtype: int64

In [37]:
sales_clean['calculated_revenue'] = (
    sales_clean['units_sold'] * sales_clean['price']
)

sales_clean['revenue_difference'] = (
    sales_clean['revenue'] -
    sales_clean['calculated_revenue']
)

valid_comparison = sales_clean[
    sales_clean['units_sold'].notna() &
    sales_clean['price'].notna()
]

inconsistencies = valid_comparison[
    valid_comparison['revenue_difference'].abs() > 0.01
]

print("Rows available for revenue validation:", len(valid_comparison))
print("Revenue inconsistencies:", len(inconsistencies))

print("\nBy promotion status:")
print(
    inconsistencies['promo_flag']
    .value_counts()
)

Rows available for revenue validation: 20881
Revenue inconsistencies: 3288

By promotion status:
promo_flag
1    3247
0      41
Name: count, dtype: int64

In [38]:
nonpromo_inconsistencies = inconsistencies[
    inconsistencies['promo_flag'] == 0
].copy()

print("Non-promo inconsistencies:", len(nonpromo_inconsistencies))

print(
    nonpromo_inconsistencies[
        [
            'date',
            'sku_id',
            'units_sold',
            'price',
            'revenue',
            'calculated_revenue',
            'revenue_difference'
        ]
    ].sort_values(
        'revenue_difference',
        key=abs,
        ascending=False
    ).head(50)
)

Non-promo inconsistencies: 41
            date  sku_id  units_sold    price    revenue  calculated_revenue  \
13533 2026-02-01  SKU026       840.0  6741.37  707843.85          5662750.80
5127  2026-01-03  SKU010       416.0  8525.33  443317.16          3546537.28
18241 2026-05-24  SKU035       504.0  5788.57  364679.91          2917439.28
11615 2025-04-03  SKU023       680.0  4088.42  347515.70          2780125.60
6520  2025-08-19  SKU013       136.0  7066.44  120129.48           961035.84
7640  2025-10-23  SKU015       552.0  1437.45   99184.05           793472.40
14550 2025-11-18  SKU028       504.0   687.38   43304.94           346439.52
27    2025-01-28  SKU001        58.0   637.85  274356.24            36995.30
28    2025-01-29  SKU001        55.0   637.85  260165.40            35081.75
3     2025-01-04  SKU001        74.0  7387.17  350040.72           546650.58
15    2025-01-16  SKU001        50.0  8525.33  236514.00           426266.50
5     2025-01-06  SKU001        56.0  1404.39  264895.68            78645.84
20    2025-01-21  SKU001        54.0  1437.45  255435.12            77622.30
23    2025-01-24  SKU001        61.0  7593.32  288547.08           463192.52
40    2025-02-10  SKU001        50.0  1369.57  236514.00            68478.50
33    2025-02-03  SKU001        54.0  1795.19  255435.12            96940.26
43    2025-02-13  SKU001        50.0  1693.76  236514.00            84688.00
16    2025-01-17  SKU001        40.0  8525.33  189211.20           341013.20
34    2025-02-04  SKU001        50.0  1795.19  236514.00            89759.50
30    2025-01-31  SKU001        72.0  6741.37  340580.16           485378.64
37    2025-02-07  SKU001        81.0  2955.84  383152.68           239423.04
49    2025-02-19  SKU001        49.0  1844.52  231783.72            90381.48
42    2025-02-12  SKU001        46.0  1693.76  217592.88            77912.96
41    2025-02-11  SKU001        40.0  1369.57  189211.20            54782.80
21    2025-01-22  SKU001        58.0  2416.11  274356.24           140134.38
8     2025-01-09  SKU001        65.0  6462.39  307468.20           420055.35
18    2025-01-19  SKU001        66.0  3211.11  312198.48           211933.26
47    2025-02-17  SKU001        46.0  2600.37  217592.88           119617.02
7     2025-01-08  SKU001        51.0  6462.39  241244.28           329581.89
17    2025-01-18  SKU001        58.0  3211.11  274356.24           186244.38
36    2025-02-06  SKU001        48.0  2955.84  227053.44           141880.32
46    2025-02-16  SKU001        44.0  3010.64  208132.32           132468.16
24    2025-01-25  SKU001        51.0  3475.70  241244.28           177260.70
19    2025-01-20  SKU001        41.0  3211.11  193941.48           131655.51
44    2025-02-14  SKU001        63.0  5549.02  298007.64           349588.26
38    2025-02-08  SKU001        51.0  5551.47  241244.28           283124.97
45    2025-02-15  SKU001        50.0  5549.02  236514.00           277451.00
31    2025-02-01  SKU001        61.0  4221.74  288547.08           257526.14
29    2025-01-30  SKU001        40.0  4175.17  189211.20           167006.80
26    2025-01-27  SKU001        58.0  4670.21  274356.24           270872.18
2     2025-01-03  SKU001        49.0  4664.22  231783.72           228546.78

       revenue_difference
13533         -4954906.95
5127          -3103220.12
18241         -2552759.37
11615         -2432609.90
6520           -840906.36
7640           -694288.35
14550          -303134.58
27              237360.94
28              225083.65
3              -196609.86
15             -189752.50
5               186249.84
20              177812.82
23             -174645.44
40              168035.50
33              158494.86
43              151826.00
16             -151802.00
34              146754.50
30             -144798.48
37              143729.64
49              141402.24
42              139679.92
41              134428.40
21              134221.86
8              -112587.15
18              100265.22
47               97975.86
7               -88337.61
17               88111.86
36               85173.12
46               75664.16
24               63983.58
19               62285.97
44              -51580.62
38              -41880.69
45              -40937.00
31               31020.94
29               22204.40
26                3484.06
2                 3236.94

In [39]:
price_validation = sales_clean.merge(
    sku_master_clean[['sku_id', 'list_price']],
    on='sku_id',
    how='left'
)

price_validation['price_difference'] = (
    price_validation['price'] -
    price_validation['list_price']
)

price_validation['price_matches_master'] = (
    price_validation['price_difference'].abs() <= 0.01
)

nonpromo_price_mismatch = price_validation[
    (price_validation['promo_flag'] == 0) &
    (~price_validation['price_matches_master']) &
    (price_validation['price'].notna())
]

print("Non-promo records with price mismatch:",
      len(nonpromo_price_mismatch))

print("\nPrice mismatch by SKU:")
print(
    nonpromo_price_mismatch['sku_id']
    .value_counts()
)

print("\nSample:")
print(
    nonpromo_price_mismatch[
        [
            'date',
            'sku_id',
            'units_sold',
            'price',
            'list_price',
            'revenue'
        ]
    ].head(30)
)

Non-promo records with price mismatch: 34

Price mismatch by SKU:
sku_id
SKU001    34
Name: count, dtype: int64

Sample:
         date  sku_id  units_sold    price  list_price    revenue
2  2025-01-03  SKU001        49.0  4664.22     4730.28  231783.72
3  2025-01-04  SKU001        74.0  7387.17     4730.28  350040.72
5  2025-01-06  SKU001        56.0  1404.39     4730.28  264895.68
7  2025-01-08  SKU001        51.0  6462.39     4730.28  241244.28
8  2025-01-09  SKU001        65.0  6462.39     4730.28  307468.20
15 2025-01-16  SKU001        50.0  8525.33     4730.28  236514.00
16 2025-01-17  SKU001        40.0  8525.33     4730.28  189211.20
17 2025-01-18  SKU001        58.0  3211.11     4730.28  274356.24
18 2025-01-19  SKU001        66.0  3211.11     4730.28  312198.48
19 2025-01-20  SKU001        41.0  3211.11     4730.28  193941.48
20 2025-01-21  SKU001        54.0  1437.45     4730.28  255435.12
21 2025-01-22  SKU001        58.0  2416.11     4730.28  274356.24
23 2025-01-24  SKU001        61.0  7593.32     4730.28  288547.08
24 2025-01-25  SKU001        51.0  3475.70     4730.28  241244.28
26 2025-01-27  SKU001        58.0  4670.21     4730.28  274356.24
27 2025-01-28  SKU001        58.0   637.85     4730.28  274356.24
28 2025-01-29  SKU001        55.0   637.85     4730.28  260165.40
29 2025-01-30  SKU001        40.0  4175.17     4730.28  189211.20
30 2025-01-31  SKU001        72.0  6741.37     4730.28  340580.16
31 2025-02-01  SKU001        61.0  4221.74     4730.28  288547.08
33 2025-02-03  SKU001        54.0  1795.19     4730.28  255435.12
34 2025-02-04  SKU001        50.0  1795.19     4730.28  236514.00
36 2025-02-06  SKU001        48.0  2955.84     4730.28  227053.44
37 2025-02-07  SKU001        81.0  2955.84     4730.28  383152.68
38 2025-02-08  SKU001        51.0  5551.47     4730.28  241244.28
40 2025-02-10  SKU001        50.0  1369.57     4730.28  236514.00
41 2025-02-11  SKU001        40.0  1369.57     4730.28  189211.20
42 2025-02-12  SKU001        46.0  1693.76     4730.28  217592.88
43 2025-02-13  SKU001        50.0  1693.76     4730.28  236514.00
44 2025-02-14  SKU001        63.0  5549.02     4730.28  298007.64

In [40]:
sku001_mismatch = nonpromo_price_mismatch[
    nonpromo_price_mismatch['sku_id'] == 'SKU001'
].copy()

sku001_mismatch['revenue_using_master_price'] = (
    sku001_mismatch['units_sold'] *
    sku001_mismatch['list_price']
)

sku001_mismatch['master_price_difference'] = (
    sku001_mismatch['revenue'] -
    sku001_mismatch['revenue_using_master_price']
)

print("SKU001 mismatched records:", len(sku001_mismatch))

print(
    "Records matching revenue using master price:",
    (
        sku001_mismatch['master_price_difference'].abs() <= 0.01
    ).sum()
)

print(
    "Records NOT matching revenue using master price:",
    (
        sku001_mismatch['master_price_difference'].abs() > 0.01
    ).sum()
)

SKU001 mismatched records: 34
Records matching revenue using master price: 34
Records NOT matching revenue using master price: 0

In [41]:
# Correct the 34 confirmed SKU001 non-promo price errors
sku001_indices = sku001_mismatch.index

sales_clean.loc[
    sku001_indices,
    'price'
] = sku001_mismatch['list_price'].values

print(
    "SKU001 prices corrected:",
    len(sku001_indices)
)

print(
    "Remaining non-promo price mismatches:",
    (
        sales_clean.merge(
            sku_master_clean[['sku_id', 'list_price']],
            on='sku_id',
            how='left'
        )
        .query("promo_flag == 0")
        .assign(
            price_diff=lambda x:
                (x['price'] - x['list_price']).abs()
        )['price_diff'] > 0.01
    ).sum()
)

SKU001 prices corrected: 34
Remaining non-promo price mismatches: 0

In [42]:
sales_clean['calculated_revenue'] = (
    sales_clean['units_sold'] * sales_clean['price']
)

sales_clean['revenue_difference'] = (
    sales_clean['revenue'] -
    sales_clean['calculated_revenue']
)

valid_comparison = sales_clean[
    sales_clean['units_sold'].notna() &
    sales_clean['price'].notna()
]

inconsistencies = valid_comparison[
    valid_comparison['revenue_difference'].abs() > 0.01
]

print("Rows available for revenue validation:", len(valid_comparison))
print("Revenue inconsistencies:", len(inconsistencies))

print("\nBy promotion status:")
print(
    inconsistencies['promo_flag'].value_counts()
)

Rows available for revenue validation: 20881
Revenue inconsistencies: 3254

By promotion status:
promo_flag
1    3247
0       7
Name: count, dtype: int64

In [43]:
remaining_nonpromo = inconsistencies[
    inconsistencies['promo_flag'] == 0
].copy()

print(
    remaining_nonpromo[
        [
            'date',
            'sku_id',
            'units_sold',
            'price',
            'revenue',
            'calculated_revenue',
            'revenue_difference'
        ]
    ]
)

            date  sku_id  units_sold    price    revenue  calculated_revenue  \
5127  2026-01-03  SKU010       416.0  8525.33  443317.16          3546537.28
6520  2025-08-19  SKU013       136.0  7066.44  120129.48           961035.84
7640  2025-10-23  SKU015       552.0  1437.45   99184.05           793472.40
11615 2025-04-03  SKU023       680.0  4088.42  347515.70          2780125.60
13533 2026-02-01  SKU026       840.0  6741.37  707843.85          5662750.80
14550 2025-11-18  SKU028       504.0   687.38   43304.94           346439.52
18241 2026-05-24  SKU035       504.0  5788.57  364679.91          2917439.28

       revenue_difference
5127          -3103220.12
6520           -840906.36
7640           -694288.35
11615         -2432609.90
13533         -4954906.95
14550          -303134.58
18241         -2552759.37

In [44]:
sales_clean['revenue_consistency_flag'] = 'OK'

sales_clean.loc[
    sales_clean['units_sold'].isna() |
    sales_clean['price'].isna(),
    'revenue_consistency_flag'
] = 'MISSING_INPUT'

sales_clean.loc[
    (
        sales_clean['units_sold'].notna() &
        sales_clean['price'].notna() &
        (sales_clean['revenue_difference'].abs() > 0.01)
    ),
    'revenue_consistency_flag'
] = 'REVENUE_MISMATCH'

print(
    sales_clean['revenue_consistency_flag'].value_counts()
)

revenue_consistency_flag
OK                  17627
REVENUE_MISMATCH     3254
MISSING_INPUT          25
Name: count, dtype: int64

In [45]:
inventory_clean['inventory_quality_flag'] = 'OK'

# Missing on-hand inventory
inventory_clean.loc[
    inventory_clean['on_hand_units'].isna(),
    'inventory_quality_flag'
] = 'MISSING_ON_HAND'

# Negative on-hand inventory
inventory_clean.loc[
    inventory_clean['on_hand_units'] < 0,
    'inventory_quality_flag'
] = 'NEGATIVE_ON_HAND'

print(
    inventory_clean['inventory_quality_flag'].value_counts()
)

inventory_quality_flag
OK                  21799
MISSING_ON_HAND        40
NEGATIVE_ON_HAND        1
Name: count, dtype: int64

In [46]:
print("Missing unit_cost:")
print(
    sku_master_clean[
        sku_master_clean['unit_cost'].isna()
    ]
)

print("\nUnique subcategories:")
print(
    sku_master_clean['subcategory'].value_counts(dropna=False)
)

print("\nSubcategories with leading/trailing spaces:")
print(
    sku_master_clean[
        sku_master_clean['subcategory']
        != sku_master_clean['subcategory'].str.strip()
    ][
        ['sku_id', 'category', 'subcategory']
    ]
)

Missing unit_cost:
    sku_id    category subcategory launch_date  unit_cost  list_price
17  SKU018  Home Decor       Clock  2024-08-06        NaN      3475.7

Unique subcategories:
subcategory
Chair         10
Toaster       10
Organizer     10
Clock          9
home decor     1
Name: count, dtype: int64

Subcategories with leading/trailing spaces:
Empty DataFrame
Columns: [sku_id, category, subcategory]
Index: []

In [47]:
sku_master_clean['sku_quality_flag'] = 'OK'

# Missing unit cost
sku_master_clean.loc[
    sku_master_clean['unit_cost'].isna(),
    'sku_quality_flag'
] = 'MISSING_UNIT_COST'

# Unusual subcategory
sku_master_clean.loc[
    sku_master_clean['subcategory'].str.lower() == 'home decor',
    'sku_quality_flag'
] = 'UNUSUAL_SUBCATEGORY'

print(
    sku_master_clean['sku_quality_flag'].value_counts()
)

sku_quality_flag
OK                     38
UNUSUAL_SUBCATEGORY     1
MISSING_UNIT_COST       1
Name: count, dtype: int64

In [48]:
# SKU referential integrity
sales_skus = set(sales_clean['sku_id'].dropna().unique())
inventory_skus = set(inventory_clean['sku_id'].dropna().unique())
master_skus = set(sku_master_clean['sku_id'].dropna().unique())

print("Sales SKUs missing from Master:",
      len(sales_skus - master_skus))

print("Inventory SKUs missing from Master:",
      len(inventory_skus - master_skus))

# Date referential integrity
calendar_dates = set(calendar_clean['date'].dropna().unique())

sales_dates = set(sales_clean['date'].dropna().unique())
inventory_dates = set(inventory_clean['date'].dropna().unique())

print("Sales dates missing from Calendar:",
      len(sales_dates - calendar_dates))

print("Inventory dates missing from Calendar:",
      len(inventory_dates - calendar_dates))

print("\nMissing Sales SKUs:")
print(sales_skus - master_skus)

print("\nMissing Inventory SKUs:")
print(inventory_skus - master_skus)

Sales SKUs missing from Master: 0
Inventory SKUs missing from Master: 0
Sales dates missing from Calendar: 0
Inventory dates missing from Calendar: 0

Missing Sales SKUs:
set()

Missing Inventory SKUs:
set()

In [49]:
print("========== PROJECT FORESIGHT — WEEK 1 DATA QUALITY SUMMARY ==========\n")

print("SALES DAILY")
print("Rows:", len(sales_clean))
print("Missing units_sold:", sales_clean['units_sold'].isna().sum())
print("Missing price:", sales_clean['price'].isna().sum())
print("Duplicate rows:", sales_clean.duplicated().sum())
print("Revenue mismatches:",
      (sales_clean['revenue_consistency_flag'] == 'REVENUE_MISMATCH').sum())
print("Missing-input records:",
      (sales_clean['revenue_consistency_flag'] == 'MISSING_INPUT').sum())

print("\nSKU MASTER")
print("Rows:", len(sku_master_clean))
print("Missing unit_cost:", sku_master_clean['unit_cost'].isna().sum())
print("Duplicate SKU IDs:", sku_master_clean['sku_id'].duplicated().sum())
print("Unusual subcategory:",
      (sku_master_clean['sku_quality_flag'] == 'UNUSUAL_SUBCATEGORY').sum())

print("\nCALENDAR")
print("Rows:", len(calendar_clean))
print("Missing dates:", calendar_clean['date'].isna().sum())
print("Duplicate dates:", calendar_clean['date'].duplicated().sum())
print("Promo-event records:", calendar_clean['promo_event'].notna().sum())

print("\nINVENTORY")
print("Rows:", len(inventory_clean))
print("Missing on_hand_units:", inventory_clean['on_hand_units'].isna().sum())
print("Missing lead_time_days:", inventory_clean['lead_time_days'].isna().sum())
print("Negative on_hand_units:",
      (inventory_clean['on_hand_units'] < 0).sum())
print("Inventory quality issues:",
      (inventory_clean['inventory_quality_flag'] != 'OK').sum())

print("\nCROSS-DATASET INTEGRITY")
print("Sales SKUs missing from Master:", len(sales_skus - master_skus))
print("Inventory SKUs missing from Master:", len(inventory_skus - master_skus))
print("Sales dates missing from Calendar:", len(sales_dates - calendar_dates))
print("Inventory dates missing from Calendar:", len(inventory_dates - calendar_dates))

========== PROJECT FORESIGHT — WEEK 1 DATA QUALITY SUMMARY ==========

SALES DAILY
Rows: 20906
Missing units_sold: 15
Missing price: 10
Duplicate rows: 0
Revenue mismatches: 3254
Missing-input records: 25

SKU MASTER
Rows: 40
Missing unit_cost: 1
Duplicate SKU IDs: 0
Unusual subcategory: 1

CALENDAR
Rows: 546
Missing dates: 0
Duplicate dates: 0
Promo-event records: 85

INVENTORY
Rows: 21840
Missing on_hand_units: 40
Missing lead_time_days: 0
Negative on_hand_units: 1
Inventory quality issues: 41

CROSS-DATASET INTEGRITY
Sales SKUs missing from Master: 0
Inventory SKUs missing from Master: 0
Sales dates missing from Calendar: 0
Inventory dates missing from Calendar: 0