# Project FORESIGHT — Data Profiling & Data Quality Assessment

## AI-Powered Demand & Inventory Intelligence Platform

### Week 1 — Data Profiling & Data Quality

### Objective

The objective of this notebook is to load, profile, validate, and assess the quality of the four core FORESIGHT datasets:

1. Sales
2. SKU Master
3. Calendar
4. Inventory

The analysis focuses on:

- Dataset structure
- Data types and schema
- Missing values
- Duplicate records
- Date range validation
- Invalid and negative values
- SKU standardization
- SKU Master validation
- Calendar validation
- Inventory validation
- Cross-dataset referential integrity
- Revenue consistency
- Data quality summary
- Preparation of cleaned datasets

The outputs of this notebook will serve as the foundation for Week 2 Exploratory Data Analysis and subsequent demand forecasting activities.

## 1. Import Libraries

The following Python libraries are used for data loading, manipulation, numerical calculations, and data-quality validation.

In [1]:
import os
import pandas as pd
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# Define paths for the four FORESIGHT datasets

sales_path = "../data/raw/sales_daily.csv"
sku_master_path = "../data/raw/sku_master.csv"
calendar_path = "../data/raw/calendar.csv"
inventory_path = "../data/raw/inventory_snapshots.csv"

print("Dataset paths defined successfully.")

Dataset paths defined successfully.

In [4]:
# Load the four FORESIGHT source datasets

sales = pd.read_csv(sales_path)
sku_master = pd.read_csv(sku_master_path)
calendar = pd.read_csv(calendar_path)
inventory = pd.read_csv(inventory_path)

print("All four datasets loaded successfully.")

NameError: name 'pd' is not defined

In [5]:
# Core libraries for data profiling

import pandas as pd
import numpy as np

print("Libraries imported successfully.")

Libraries imported successfully.

In [6]:
# Define paths for the four FORESIGHT datasets

sales_path = "../data/raw/sales_daily.csv"
sku_master_path = "../data/raw/sku_master.csv"
calendar_path = "../data/raw/calendar.csv"
inventory_path = "../data/raw/inventory_snapshots.csv"

print("Dataset paths defined successfully.")

Dataset paths defined successfully.

In [8]:
# Load the FORESIGHT analysis-ready dataset

file_path = "../data/processed/analysis_ready.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (20906, 26)

In [9]:
# Check the basic structure of the dataset

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

Number of rows: 20906
Number of columns: 26

Column names:
['date', 'sku_id', 'units_sold', 'revenue', 'price', 'promo_flag', 'calculated_revenue', 'revenue_difference', 'revenue_consistency_flag', 'category', 'subcategory', 'launch_date', 'unit_cost', 'list_price', 'sku_quality_flag', 'week', 'month', 'season', 'is_holiday', 'promo_event', 'promo_flag_calendar', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point', 'inventory_quality_flag']

In [10]:
# Check data types and non-null values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20906 entries, 0 to 20905
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      20906 non-null  str
 1   sku_id                    20906 non-null  str
 2   units_sold                20891 non-null  float64
 3   revenue                   20906 non-null  float64
 4   price                     20896 non-null  float64
 5   promo_flag                20906 non-null  int64
 6   calculated_revenue        20881 non-null  float64
 7   revenue_difference        20881 non-null  float64
 8   revenue_consistency_flag  20906 non-null  str
 9   category                  20906 non-null  str
 10  subcategory               20906 non-null  str
 11  launch_date               20906 non-null  str
 12  unit_cost                 20360 non-null  float64
 13  list_price                20906 non-null  float64
 14  sku_quality_flag          20906 non-null  str
 15  week                      20906 non-null  int64
 16  month                     20906 non-null  int64
 17  season                    20906 non-null  str
 18  is_holiday                20906 non-null  int64
 19  promo_event               3272 non-null   str
 20  promo_flag_calendar       20906 non-null  int64
 21  on_hand_units             20866 non-null  float64
 22  on_order_units            20906 non-null  int64
 23  lead_time_days            20906 non-null  float64
 24  reorder_point             20906 non-null  int64
 25  inventory_quality_flag    20906 non-null  str
dtypes: float64(9), int64(7), str(10)
memory usage: 5.3 MB

In [11]:
# Display the first 5 records

df.head()

,date,sku_id,units_sold,revenue,price,promo_flag,calculated_revenue,revenue_difference,revenue_consistency_flag,category,...,month,season,is_holiday,promo_event,promo_flag_calendar,on_hand_units,on_order_units,lead_time_days,reorder_point,inventory_quality_flag
0,2025-01-01,SKU001,52.0,245974.56,4730.28,0,245974.56,0.000000e+00,OK,Furniture,...,1,Winter,0,NaN,0,284.0,125,6.0,255,OK
1,2025-01-02,SKU001,69.0,326389.32,4730.28,0,326389.32,0.000000e+00,OK,Furniture,...,1,Winter,0,NaN,0,215.0,128,6.0,255,OK
2,2025-01-03,SKU001,49.0,231783.72,4664.22,0,228546.78,3.236940e+03,REVENUE_MISMATCH,Furniture,...,1,Winter,0,NaN,0,166.0,186,6.0,255,OK
3,2025-01-04,SKU001,74.0,350040.72,7387.17,0,546650.58,-1.966099e+05,REVENUE_MISMATCH,Furniture,...,1,Winter,0,NaN,0,92.0,62,6.0,255,OK
4,2025-01-05,SKU001,43.0,203402.04,4730.28,0,203402.04,2.910383e-11,OK,Furniture,...,1,Winter,0,NaN,0,49.0,112,6.0,255,OK

In [12]:
# Check missing values in every column

missing_values = df.isnull().sum()

missing_values = (
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

missing_values

promo_event           17634
unit_cost               546
on_hand_units            40
calculated_revenue       25
revenue_difference       25
units_sold               15
price                    10
dtype: int64

In [13]:
# Calculate missing-value percentage

missing_percentage = (
    df.isnull().sum()
    / len(df)
    * 100
)

missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_summary = (
    missing_summary[missing_summary["Missing_Count"] > 0]
    .sort_values("Missing_Count", ascending=False)
)

missing_summary

                    Missing_Count  Missing_Percentage
promo_event                 17634           84.348991
unit_cost                     546            2.611690
on_hand_units                  40            0.191333
calculated_revenue             25            0.119583
revenue_difference             25            0.119583
units_sold                     15            0.071750
price                          10            0.047833

In [14]:
# Check for completely duplicated records

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [15]:
# Display data types of all columns

dtype_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values
})

dtype_summary

                      Column Data_Type
0                       date       str
1                     sku_id       str
2                 units_sold   float64
3                    revenue   float64
4                      price   float64
5                 promo_flag     int64
6         calculated_revenue   float64
7         revenue_difference   float64
8   revenue_consistency_flag       str
9                   category       str
10               subcategory       str
11               launch_date       str
12                 unit_cost   float64
13                list_price   float64
14          sku_quality_flag       str
15                      week     int64
16                     month     int64
17                    season       str
18                is_holiday     int64
19               promo_event       str
20       promo_flag_calendar     int64
21             on_hand_units   float64
22            on_order_units     int64
23            lead_time_days   float64
24             reorder_point     int64
25    inventory_quality_flag       str

In [16]:
# Identify numerical columns

numerical_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

print("Numerical columns:")
for column in numerical_columns:
    print("-", column)

Numerical columns:
- units_sold
- revenue
- price
- promo_flag
- calculated_revenue
- revenue_difference
- unit_cost
- list_price
- week
- month
- is_holiday
- promo_flag_calendar
- on_hand_units
- on_order_units
- lead_time_days
- reorder_point

In [17]:
# Generate descriptive statistics for numerical columns

df[numerical_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
units_sold,20891.0,60.829783,34.378615,1.00,34.00,59.000,83.00,840.00
revenue,20906.0,235449.013888,200088.596680,7387.17,89121.90,156915.675,327322.67,1484829.09
price,20896.0,4070.395135,2168.798149,637.85,1844.52,4088.420,5788.57,8525.33
promo_flag,20906.0,0.156510,0.363347,0.00,0.00,0.000,0.00,1.00
calculated_revenue,20881.0,239930.180970,211446.973112,7387.17,90101.13,160921.580,331119.60,5662750.80
revenue_difference,20881.0,-4513.102803,49838.258292,-4954906.95,0.00,0.000,0.00,237360.94
unit_cost,20360.0,2492.511256,1259.409723,334.60,1366.47,2362.730,3577.63,4847.30
list_price,20906.0,4071.884657,2166.808288,637.85,1844.52,4088.420,5788.57,8525.33
week,20906.0,22.920980,14.241605,1.00,11.00,21.000,34.00,52.00
month,20906.0,5.678370,3.289357,1.00,3.00,5.000,8.00,12.00
is_holiday,20906.0,0.011002,0.104313,0.00,0.00,0.000,0.00,1.00
promo_flag_calendar,20906.0,0.156510,0.363347,0.00,0.00,0.000,0.00,1.00
on_hand_units,20866.0,20.867536,76.400982,-25.00,0.00,0.000,0.00,1436.00
on_order_units,20906.0,91.305176,79.939978,0.00,28.00,71.000,142.00,349.00
lead_time_days,20906.0,7.729982,3.766675,2.00,5.00,7.000,11.00,14.00
reorder_point,20906.0,340.341385,260.133322,48.00,129.00,255.000,460.00,1231.00

In [18]:
# Check the number of unique values in each column

unique_summary = pd.DataFrame({
    "Column": df.columns,
    "Unique_Values": [
        df[column].nunique(dropna=True)
        for column in df.columns
    ]
})

unique_summary

                      Column  Unique_Values
0                       date            546
1                     sku_id             40
2                 units_sold            194
3                    revenue           3987
4                      price             44
5                 promo_flag              2
6         calculated_revenue           2860
7         revenue_difference           1738
8   revenue_consistency_flag              3
9                   category              4
10               subcategory              5
11               launch_date             39
12                 unit_cost             39
13                list_price             40
14          sku_quality_flag              3
15                      week             52
16                     month             12
17                    season              4
18                is_holiday              2
19               promo_event              6
20       promo_flag_calendar              2
21             on_hand_units            463
22            on_order_units            346
23            lead_time_days             13
24             reorder_point             39
25    inventory_quality_flag              3

In [19]:
# Check negative values in numerical columns

negative_summary = {}

for column in numerical_columns:
    negative_summary[column] = (df[column] < 0).sum()

negative_summary = (
    pd.Series(negative_summary, name="Negative_Count")
    .sort_values(ascending=False)
)

negative_summary

revenue_difference     5111
on_hand_units             1
price                     0
units_sold                0
promo_flag                0
calculated_revenue        0
unit_cost                 0
revenue                   0
list_price                0
week                      0
is_holiday                0
month                     0
promo_flag_calendar       0
on_order_units            0
lead_time_days            0
reorder_point             0
Name: Negative_Count, dtype: int64

In [20]:
# Check the date column

print("Date column data type:", df["date"].dtype)

print("\nStart date:", df["date"].min())
print("End date:", df["date"].max())

print("\nMissing dates:", df["date"].isnull().sum())

Date column data type: str

Start date: 2025-01-01
End date: 2026-06-30

Missing dates: 0

In [21]:
# Convert date column to datetime for reliable date analysis

df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

print("Date conversion completed.")
print("Date data type:", df["date"].dtype)

Date conversion completed.
Date data type: datetime64[us]

In [22]:
# Check for invalid dates after conversion

invalid_dates = df["date"].isna().sum()

print("Invalid date values:", invalid_dates)

print("\nDate range:")
print("Start:", df["date"].min())
print("End:", df["date"].max())

Invalid date values: 0

Date range:
Start: 2025-01-01 00:00:00
End: 2026-06-30 00:00:00

In [23]:
# Check SKU coverage

print("Total SKU records:", len(df["sku_id"]))
print("Unique SKUs:", df["sku_id"].nunique())
print("Missing SKU IDs:", df["sku_id"].isna().sum())

Total SKU records: 20906
Unique SKUs: 40
Missing SKU IDs: 0

In [24]:
# Check for whitespace and inconsistent SKU formatting

sku_as_string = df["sku_id"].astype(str)

leading_or_trailing_spaces = (
    sku_as_string != sku_as_string.str.strip()
).sum()

lowercase_skus = (
    sku_as_string != sku_as_string.str.upper()
).sum()

print("SKUs with leading/trailing spaces:", leading_or_trailing_spaces)
print("SKUs containing lowercase characters:", lowercase_skus)

SKUs with leading/trailing spaces: 0
SKUs containing lowercase characters: 0

In [25]:
# Check revenue consistency

revenue_check = df["revenue_consistency_flag"].value_counts(
    dropna=False
)

print("Revenue consistency status:")
print(revenue_check)

Revenue consistency status:
revenue_consistency_flag
OK                  17593
REVENUE_MISMATCH     3288
MISSING_INPUT          25
Name: count, dtype: int64

In [26]:
# Summarize revenue differences

revenue_difference_summary = df["revenue_difference"].describe()

revenue_difference_summary

count    2.088100e+04
mean    -4.513103e+03
std      4.983826e+04
min     -4.954907e+06
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.373609e+05
Name: revenue_difference, dtype: float64

In [27]:
# Display records where revenue does not match calculated revenue

revenue_mismatches = df[
    df["revenue_consistency_flag"] == "REVENUE_MISMATCH"
]

print("Number of revenue mismatch records:",
      len(revenue_mismatches))

revenue_mismatches[
    [
        "date",
        "sku_id",
        "units_sold",
        "price",
        "revenue",
        "calculated_revenue",
        "revenue_difference"
    ]
].head(20)

Number of revenue mismatch records: 3288

,date,sku_id,units_sold,price,revenue,calculated_revenue,revenue_difference
2,2025-01-03,SKU001,49.0,4664.22,231783.72,228546.78,3236.94
3,2025-01-04,SKU001,74.0,7387.17,350040.72,546650.58,-196609.86
5,2025-01-06,SKU001,56.0,1404.39,264895.68,78645.84,186249.84
7,2025-01-08,SKU001,51.0,6462.39,241244.28,329581.89,-88337.61
8,2025-01-09,SKU001,65.0,6462.39,307468.20,420055.35,-112587.15
9,2025-01-10,SKU001,70.0,3737.54,304630.03,261627.80,43002.23
10,2025-01-11,SKU001,84.0,4730.28,365556.04,397343.52,-31787.48
11,2025-01-12,SKU001,59.0,3737.54,256759.60,220514.86,36244.74
12,2025-01-13,SKU001,43.0,7237.42,187129.88,311209.06,-124079.18
13,2025-01-14,SKU001,66.0,7237.42,287222.60,477669.72,-190447.12
14,2025-01-15,SKU001,74.0,4272.13,322037.46,316137.62,5899.84
15,2025-01-16,SKU001,50.0,8525.33,236514.00,426266.50,-189752.50
16,2025-01-17,SKU001,40.0,8525.33,189211.20,341013.20,-151802.00
17,2025-01-18,SKU001,58.0,3211.11,274356.24,186244.38,88111.86
18,2025-01-19,SKU001,66.0,3211.11,312198.48,211933.26,100265.22
19,2025-01-20,SKU001,41.0,3211.11,193941.48,131655.51,62285.97
20,2025-01-21,SKU001,54.0,1437.45,255435.12,77622.30,177812.82
21,2025-01-22,SKU001,58.0,2416.11,274356.24,140134.38,134221.86
23,2025-01-24,SKU001,61.0,7593.32,288547.08,463192.52,-174645.44
24,2025-01-25,SKU001,51.0,3475.70,241244.28,177260.70,63983.58

In [28]:
# Check inventory-related fields

inventory_columns = [
    "on_hand_units",
    "on_order_units"
]

inventory_quality = pd.DataFrame({
    "Missing_Count": df[inventory_columns].isnull().sum(),
    "Negative_Count": (df[inventory_columns] < 0).sum(),
    "Unique_Values": df[inventory_columns].nunique()
})

inventory_quality

                Missing_Count  Negative_Count  Unique_Values
on_hand_units              40               1            463
on_order_units              0               0            346

In [29]:
# Create a consolidated quality summary for key business fields

quality_summary = pd.DataFrame({
    "Metric": [
        "Total Records",
        "Unique SKUs",
        "Missing Units Sold",
        "Missing Revenue",
        "Missing Price",
        "Missing On-Hand Units",
        "Missing On-Order Units",
        "Duplicate Rows",
        "Revenue Mismatch Records"
    ],
    "Count": [
        len(df),
        df["sku_id"].nunique(),
        df["units_sold"].isnull().sum(),
        df["revenue"].isnull().sum(),
        df["price"].isnull().sum(),
        df["on_hand_units"].isnull().sum(),
        df["on_order_units"].isnull().sum(),
        df.duplicated().sum(),
        (df["revenue_consistency_flag"] == "REVENUE_MISMATCH").sum()
    ]
})

quality_summary

                     Metric  Count
0             Total Records  20906
1               Unique SKUs     40
2        Missing Units Sold     15
3           Missing Revenue      0
4             Missing Price     10
5     Missing On-Hand Units     40
6    Missing On-Order Units      0
7            Duplicate Rows      0
8  Revenue Mismatch Records   3288

In [30]:
# Inspect promotional information

promo_columns = [
    column for column in df.columns
    if any(keyword in column.lower()
           for keyword in ["promo", "promotion"])
]

print("Promotional columns:")
for column in promo_columns:
    print("-", column)

Promotional columns:
- promo_flag
- promo_event
- promo_flag_calendar

In [31]:
# Check the values of promotional fields

for column in promo_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- promo_flag ---
promo_flag
0    17634
1     3272
Name: count, dtype: int64

--- promo_event ---
promo_event
NaN              17634
Summer Sale        880
Spring Sale        712
Year End Sale      680
Black Friday       440
Festive Sale       400
New Year Sale      160
Name: count, dtype: int64

--- promo_flag_calendar ---
promo_flag_calendar
0    17634
1     3272
Name: count, dtype: int64

In [32]:
# Identify categorical/object columns

categorical_columns = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Categorical columns:")
for column in categorical_columns:
    print("-", column)

Categorical columns:
- sku_id
- revenue_consistency_flag
- category
- subcategory
- launch_date
- sku_quality_flag
- season
- promo_event
- inventory_quality_flag

C:\Users\sharkon\AppData\Local\Temp\ipykernel_19808\1278805103.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [33]:
# Check the values of promotional fields

for column in promo_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- promo_flag ---
promo_flag
0    17634
1     3272
Name: count, dtype: int64

--- promo_event ---
promo_event
NaN              17634
Summer Sale        880
Spring Sale        712
Year End Sale      680
Black Friday       440
Festive Sale       400
New Year Sale      160
Name: count, dtype: int64

--- promo_flag_calendar ---
promo_flag_calendar
0    17634
1     3272
Name: count, dtype: int64

In [34]:
# Identify categorical/object columns

categorical_columns = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Categorical columns:")
for column in categorical_columns:
    print("-", column)

Categorical columns:
- sku_id
- revenue_consistency_flag
- category
- subcategory
- launch_date
- sku_quality_flag
- season
- promo_event
- inventory_quality_flag

C:\Users\sharkon\AppData\Local\Temp\ipykernel_19808\1278805103.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [35]:
# Display the most common values for categorical columns

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False).head(10))

--- sku_id ---
sku_id
SKU001    546
SKU003    546
SKU005    546
SKU006    546
SKU007    546
SKU008    546
SKU009    546
SKU012    546
SKU016    546
SKU018    546
Name: count, dtype: int64

--- revenue_consistency_flag ---
revenue_consistency_flag
OK                  17593
REVENUE_MISMATCH     3288
MISSING_INPUT          25
Name: count, dtype: int64

--- category ---
category
Home Decor          5421
Small Appliances    5355
Office              5279
Furniture           4851
Name: count, dtype: int64

--- subcategory ---
subcategory
Toaster       5355
Organizer     5279
Clock         4875
Chair         4851
home decor     546
Name: count, dtype: int64

--- launch_date ---
launch_date
2025-01-14    1066
2024-02-14     546
2024-09-20     546
2024-09-07     546
2024-07-04     546
2024-08-13     546
2024-04-23     546
2024-03-23     546
2024-04-07     546
2024-04-04     546
Name: count, dtype: int64

--- sku_quality_flag ---
sku_quality_flag
OK                     19814
UNUSUAL_SUBCATEGORY      546
MISSING_UNIT_COST        546
Name: count, dtype: int64

--- season ---
season
Spring    7032
Winter    5354
Summer    4880
Autumn    3640
Name: count, dtype: int64

--- promo_event ---
promo_event
NaN              17634
Summer Sale        880
Spring Sale        712
Year End Sale      680
Black Friday       440
Festive Sale       400
New Year Sale      160
Name: count, dtype: int64

--- inventory_quality_flag ---
inventory_quality_flag
OK                  20865
MISSING_ON_HAND        40
NEGATIVE_ON_HAND        1
Name: count, dtype: int64

In [36]:
# Create a final profiling summary

profiling_summary = pd.DataFrame({
    "Metric": [
        "Total Records",
        "Total Columns",
        "Unique SKUs",
        "Start Date",
        "End Date",
        "Duplicate Rows",
        "Total Missing Values",
        "Revenue Mismatch Records"
    ],
    "Value": [
        len(df),
        len(df.columns),
        df["sku_id"].nunique(),
        df["date"].min(),
        df["date"].max(),
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        (df["revenue_consistency_flag"] == "REVENUE_MISMATCH").sum()
    ]
})

profiling_summary

                     Metric                Value
0             Total Records                20906
1             Total Columns                   26
2               Unique SKUs                   40
3                Start Date  2025-01-01 00:00:00
4                  End Date  2026-06-30 00:00:00
5            Duplicate Rows                    0
6      Total Missing Values                18295
7  Revenue Mismatch Records                 3288

## 15. Data Quality Findings

Based on the profiling checks performed above, the following areas require attention:

- Missing values in selected business fields
- Duplicate records, if identified
- Invalid or negative numerical values, if identified
- Date-quality issues, if identified
- SKU identifier formatting issues, if identified
- Revenue consistency mismatches
- Inventory-related missing or invalid values
- Promotional-data quality exceptions, if identified

These findings should be investigated before they are used for downstream forecasting and inventory intelligence.

In [37]:
# Create a clean missing-value report for documentation

missing_report = (
    df.isnull()
    .sum()
    .reset_index()
)

missing_report.columns = ["Column", "Missing_Count"]

missing_report["Missing_Percentage"] = (
    missing_report["Missing_Count"] / len(df) * 100
)

missing_report = (
    missing_report[missing_report["Missing_Count"] > 0]
    .sort_values("Missing_Count", ascending=False)
)

missing_report

                Column  Missing_Count  Missing_Percentage
19         promo_event          17634           84.348991
12           unit_cost            546            2.611690
21       on_hand_units             40            0.191333
6   calculated_revenue             25            0.119583
7   revenue_difference             25            0.119583
2           units_sold             15            0.071750
4                price             10            0.047833

In [38]:
# Create a duplicate-record report

duplicate_report = pd.DataFrame({
    "Metric": ["Total Duplicate Rows"],
    "Count": [df.duplicated().sum()]
})

duplicate_report

                 Metric  Count
0  Total Duplicate Rows      0

In [39]:
# Create a revenue consistency report

revenue_report = pd.DataFrame({
    "Status": df["revenue_consistency_flag"].value_counts(
        dropna=False
    ).index,
    "Record_Count": df["revenue_consistency_flag"].value_counts(
        dropna=False
    ).values
})

revenue_report["Percentage"] = (
    revenue_report["Record_Count"] / len(df) * 100
)

revenue_report

             Status  Record_Count  Percentage
0                OK         17593   84.152875
1  REVENUE_MISMATCH          3288   15.727542
2     MISSING_INPUT            25    0.119583

## 16. Week 1 Conclusion

The FORESIGHT dataset has been profiled across its structure, data types, missing values, duplicates, numerical validity, dates, SKU identifiers, revenue consistency, inventory fields, and promotional attributes.

The identified data-quality exceptions should be documented and investigated before downstream modeling.

### Handoff to Week 2

The profiling results from this notebook will serve as the foundation for:

- Exploratory Data Analysis (EDA)
- Demand pattern analysis
- SKU-level performance analysis
- Revenue and sales analysis
- Inventory analysis
- Promotional impact analysis
- Seasonality analysis
- Feature engineering
- Demand forecasting

In [41]:
# Create an overall data-quality status

quality_checks = {
    "Missing Values": df.isnull().sum().sum(),
    "Duplicate Rows": df.duplicated().sum(),
    "Invalid Dates": df["date"].isna().sum(),
    "Negative Units Sold": (df["units_sold"] < 0).sum(),
    "Negative Revenue": (df["revenue"] < 0).sum(),
    "Revenue Mismatches": (
        df["revenue_consistency_flag"] == "REVENUE_MISMATCH"
    ).sum()
}

quality_status = pd.DataFrame(
    list(quality_checks.items()),
    columns=["Quality_Check", "Issue_Count"]
)

quality_status

         Quality_Check  Issue_Count
0       Missing Values        18295
1       Duplicate Rows            0
2        Invalid Dates            0
3  Negative Units Sold            0
4     Negative Revenue            0
5   Revenue Mismatches         3288

In [42]:
# Identify columns containing missing values

columns_with_missing_values = (
    df.isnull()
    .sum()
)

columns_with_missing_values = (
    columns_with_missing_values[
        columns_with_missing_values > 0
    ]
    .sort_values(ascending=False)
)

columns_with_missing_values

promo_event           17634
unit_cost               546
on_hand_units            40
calculated_revenue       25
revenue_difference       25
units_sold               15
price                    10
dtype: int64

In [43]:
# Check the number of records available for each SKU

sku_record_summary = (
    df.groupby("sku_id")
      .size()
      .reset_index(name="Record_Count")
      .sort_values("Record_Count", ascending=False)
)

sku_record_summary.head(20)

    sku_id  Record_Count
0   SKU001           546
2   SKU003           546
5   SKU006           546
4   SKU005           546
6   SKU007           546
7   SKU008           546
11  SKU012           546
8   SKU009           546
35  SKU036           546
38  SKU039           546
15  SKU016           546
17  SKU018           546
21  SKU022           546
22  SKU023           546
18  SKU019           546
39  SKU040           546
33  SKU034           546
34  SKU035           546
31  SKU032           546
29  SKU030           546

In [44]:
# Save profiling reports for project documentation

missing_report.to_csv(
    "../data/processed/profiling_missing_values.csv",
    index=False
)

quality_status.to_csv(
    "../data/processed/profiling_quality_status.csv",
    index=False
)

revenue_report.to_csv(
    "../data/processed/profiling_revenue_quality.csv",
    index=False
)

sku_record_summary.to_csv(
    "../data/processed/profiling_sku_coverage.csv",
    index=False
)

print("Profiling reports exported successfully.")

Profiling reports exported successfully.

# Week 1 Profiling Handoff

The `analysis_ready.csv` dataset has been systematically profiled for:

- Dataset structure
- Data types
- Missing values
- Duplicate records
- Numerical validity
- Date quality
- SKU coverage
- Revenue consistency
- Inventory quality
- Promotional attributes

The profiling reports have been exported to the processed-data directory.

### Next Stage

The validated profiling results will be used as the starting point for:

**Week 2 — Exploratory Data Analysis (EDA)**

The EDA stage will focus on identifying demand patterns, SKU performance, sales trends, inventory behavior, seasonality, promotional effects, and business insights.