# Project FORESIGHT — Inventory Recommendations

## Inventory Recommendation Engine

This notebook uses the output generated by
`05_inventory_risk_analysis.ipynb`.

Input:
`data/processed/inventory_risk_analysis.csv`

Objectives:

- Load inventory risk analysis results
- Inspect available inventory and demand fields
- Calculate inventory position where required
- Calculate target inventory where required
- Calculate recommended replenishment quantity
- Generate inventory recommendations
- Prioritize stockout and overstock situations
- Create SKU-level recommendation summaries
- Export final recommendation files

In [33]:
# Import required libraries

import pandas as pd
import numpy as np
import os

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [44]:
# Load the FORESIGHT analysis-ready dataset

file_path = "../data/processed/analysis_ready.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (20906, 26)

In [45]:
# Convert date column to datetime

df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

print("Date conversion completed.")

Date conversion completed.

In [46]:
# Check fields required for inventory recommendations

required_columns = [
    "date",
    "sku_id",
    "on_hand_units",
    "on_order_units",
    "lead_time_days",
    "reorder_point"
]

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

if missing_columns:
    print("Missing columns:")
    for column in missing_columns:
        print("-", column)
else:
    print("All required columns are available.")

All required columns are available.

In [47]:
# Calculate inventory position

df["inventory_position"] = (
    df["on_hand_units"].fillna(0)
    + df["on_order_units"].fillna(0)
)

df[
    [
        "date",
        "sku_id",
        "on_hand_units",
        "on_order_units",
        "inventory_position"
    ]
].head(10)

        date  sku_id  on_hand_units  on_order_units  inventory_position
0 2025-01-01  SKU001          284.0             125               409.0
1 2025-01-02  SKU001          215.0             128               343.0
2 2025-01-03  SKU001          166.0             186               352.0
3 2025-01-04  SKU001           92.0              62               154.0
4 2025-01-05  SKU001           49.0             112               161.0
5 2025-01-06  SKU001           50.0               0                50.0
6 2025-01-07  SKU001            4.0              64                68.0
7 2025-01-08  SKU001            0.0             127               127.0
8 2025-01-09  SKU001            0.0              43                43.0
9 2025-01-10  SKU001            0.0              49                49.0

In [48]:
# Use existing reorder point as target inventory

df["target_inventory"] = (
    df["reorder_point"]
    .fillna(0)
)

print("Target inventory created.")

Target inventory created.

In [49]:
# Calculate recommended replenishment quantity

df["recommended_order_qty"] = (
    df["target_inventory"]
    - df["inventory_position"]
).clip(lower=0)

df["recommended_order_qty"] = (
    df["recommended_order_qty"]
    .round()
    .astype(int)
)

print("Recommended order quantity calculated.")

Recommended order quantity calculated.

In [50]:
# Preview replenishment recommendations

recommendation_preview = df[
    [
        "date",
        "sku_id",
        "on_hand_units",
        "on_order_units",
        "inventory_position",
        "reorder_point",
        "target_inventory",
        "recommended_order_qty"
    ]
].copy()

recommendation_preview.head(20)

,date,sku_id,on_hand_units,on_order_units,inventory_position,reorder_point,target_inventory,recommended_order_qty
0,2025-01-01,SKU001,284.0,125,409.0,255,255,0
1,2025-01-02,SKU001,215.0,128,343.0,255,255,0
2,2025-01-03,SKU001,166.0,186,352.0,255,255,0
3,2025-01-04,SKU001,92.0,62,154.0,255,255,101
4,2025-01-05,SKU001,49.0,112,161.0,255,255,94
5,2025-01-06,SKU001,50.0,0,50.0,255,255,205
6,2025-01-07,SKU001,4.0,64,68.0,255,255,187
7,2025-01-08,SKU001,0.0,127,127.0,255,255,128
8,2025-01-09,SKU001,0.0,43,43.0,255,255,212
9,2025-01-10,SKU001,0.0,49,49.0,255,255,206
10,2025-01-11,SKU001,0.0,65,65.0,255,255,190
11,2025-01-12,SKU001,51.0,0,51.0,255,255,204
12,2025-01-13,SKU001,8.0,187,195.0,255,255,60
13,2025-01-14,SKU001,0.0,139,139.0,255,255,116
14,2025-01-15,SKU001,0.0,135,135.0,255,255,120
15,2025-01-16,SKU001,0.0,87,87.0,255,255,168
16,2025-01-17,SKU001,0.0,39,39.0,255,255,216
17,2025-01-18,SKU001,101.0,0,101.0,255,255,154
18,2025-01-19,SKU001,35.0,30,65.0,255,255,190
19,2025-01-20,SKU001,0.0,149,149.0,255,255,106

In [51]:
# Generate inventory recommendation status

df["recommendation"] = np.where(
    df["recommended_order_qty"] > 0,
    "REPLENISH_STOCK",
    "NO_ACTION"
)

df["recommendation"].value_counts()

recommendation
REPLENISH_STOCK    19208
NO_ACTION           1698
Name: count, dtype: int64

In [53]:
# Assign recommendation priority

df["recommendation_priority"] = np.select(
    [
        df["inventory_position"] < df["reorder_point"],
        df["recommended_order_qty"] > 0
    ],
    [
        "HIGH",
        "MEDIUM"
    ],
    default="LOW"
)

df["recommendation_priority"].value_counts()

recommendation_priority
HIGH    19208
LOW      1698
Name: count, dtype: int64

In [54]:
# Create final inventory recommendation dataset

inventory_recommendations = df[
    [
        "date",
        "sku_id",
        "category",
        "subcategory",
        "units_sold",
        "on_hand_units",
        "on_order_units",
        "lead_time_days",
        "reorder_point",
        "inventory_position",
        "target_inventory",
        "recommended_order_qty",
        "inventory_quality_flag",
        "recommendation_priority",
        "recommendation"
    ]
].copy()

inventory_recommendations.head(20)

,date,sku_id,category,subcategory,units_sold,on_hand_units,on_order_units,lead_time_days,reorder_point,inventory_position,target_inventory,recommended_order_qty,inventory_quality_flag,recommendation_priority,recommendation
0,2025-01-01,SKU001,Furniture,Chair,52.0,284.0,125,6.0,255,409.0,255,0,OK,LOW,NO_ACTION
1,2025-01-02,SKU001,Furniture,Chair,69.0,215.0,128,6.0,255,343.0,255,0,OK,LOW,NO_ACTION
2,2025-01-03,SKU001,Furniture,Chair,49.0,166.0,186,6.0,255,352.0,255,0,OK,LOW,NO_ACTION
3,2025-01-04,SKU001,Furniture,Chair,74.0,92.0,62,6.0,255,154.0,255,101,OK,HIGH,REPLENISH_STOCK
4,2025-01-05,SKU001,Furniture,Chair,43.0,49.0,112,6.0,255,161.0,255,94,OK,HIGH,REPLENISH_STOCK
5,2025-01-06,SKU001,Furniture,Chair,56.0,50.0,0,6.0,255,50.0,255,205,OK,HIGH,REPLENISH_STOCK
6,2025-01-07,SKU001,Furniture,Chair,46.0,4.0,64,6.0,255,68.0,255,187,OK,HIGH,REPLENISH_STOCK
7,2025-01-08,SKU001,Furniture,Chair,51.0,0.0,127,6.0,255,127.0,255,128,OK,HIGH,REPLENISH_STOCK
8,2025-01-09,SKU001,Furniture,Chair,65.0,0.0,43,6.0,255,43.0,255,212,OK,HIGH,REPLENISH_STOCK
9,2025-01-10,SKU001,Furniture,Chair,70.0,0.0,49,6.0,255,49.0,255,206,OK,HIGH,REPLENISH_STOCK
10,2025-01-11,SKU001,Furniture,Chair,84.0,0.0,65,6.0,255,65.0,255,190,OK,HIGH,REPLENISH_STOCK
11,2025-01-12,SKU001,Furniture,Chair,59.0,51.0,0,6.0,255,51.0,255,204,OK,HIGH,REPLENISH_STOCK
12,2025-01-13,SKU001,Furniture,Chair,43.0,8.0,187,6.0,255,195.0,255,60,OK,HIGH,REPLENISH_STOCK
13,2025-01-14,SKU001,Furniture,Chair,66.0,0.0,139,6.0,255,139.0,255,116,OK,HIGH,REPLENISH_STOCK
14,2025-01-15,SKU001,Furniture,Chair,74.0,0.0,135,6.0,255,135.0,255,120,OK,HIGH,REPLENISH_STOCK
15,2025-01-16,SKU001,Furniture,Chair,50.0,0.0,87,6.0,255,87.0,255,168,OK,HIGH,REPLENISH_STOCK
16,2025-01-17,SKU001,Furniture,Chair,40.0,0.0,39,6.0,255,39.0,255,216,OK,HIGH,REPLENISH_STOCK
17,2025-01-18,SKU001,Furniture,Chair,58.0,101.0,0,6.0,255,101.0,255,154,OK,HIGH,REPLENISH_STOCK
18,2025-01-19,SKU001,Furniture,Chair,66.0,35.0,30,6.0,255,65.0,255,190,OK,HIGH,REPLENISH_STOCK
19,2025-01-20,SKU001,Furniture,Chair,41.0,0.0,149,6.0,255,149.0,255,106,OK,HIGH,REPLENISH_STOCK

In [55]:
# Export inventory recommendations

output_path = (
    "../data/processed/inventory_recommendations.csv"
)

inventory_recommendations.to_csv(
    output_path,
    index=False
)

print("Inventory recommendations exported successfully.")
print("File:", output_path)

Inventory recommendations exported successfully.
File: ../data/processed/inventory_recommendations.csv

In [56]:
# Generate inventory recommendation status

df["recommendation"] = np.where(
    df["recommended_order_qty"] > 0,
    "REPLENISH_STOCK",
    "NO_ACTION"
)

print("Recommendation status created.")

df["recommendation"].value_counts()

Recommendation status created.

recommendation
REPLENISH_STOCK    19208
NO_ACTION           1698
Name: count, dtype: int64

In [57]:
# Assign recommendation priority

df["recommendation_priority"] = np.select(
    [
        df["inventory_position"] < df["reorder_point"],
        df["recommended_order_qty"] > 0
    ],
    [
        "HIGH",
        "MEDIUM"
    ],
    default="LOW"
)

print("Recommendation priority created.")

df["recommendation_priority"].value_counts()

Recommendation priority created.

recommendation_priority
HIGH    19208
LOW      1698
Name: count, dtype: int64

In [58]:
# Create a simple inventory risk status

df["inventory_risk"] = np.select(
    [
        df["inventory_position"] < df["reorder_point"],
        df["inventory_position"] > (
            df["reorder_point"] * 1.5
        )
    ],
    [
        "STOCKOUT_RISK",
        "OVERSTOCK_RISK"
    ],
    default="HEALTHY"
)

print("Inventory risk status created.")

df["inventory_risk"].value_counts()

Inventory risk status created.

inventory_risk
STOCKOUT_RISK     19208
HEALTHY            1033
OVERSTOCK_RISK      665
Name: count, dtype: int64

In [59]:
# Create the final inventory recommendation dataset

inventory_recommendations = df[
    [
        "date",
        "sku_id",
        "category",
        "subcategory",
        "units_sold",
        "on_hand_units",
        "on_order_units",
        "lead_time_days",
        "reorder_point",
        "inventory_position",
        "target_inventory",
        "recommended_order_qty",
        "inventory_risk",
        "recommendation_priority",
        "recommendation"
    ]
].copy()

inventory_recommendations.head(20)

,date,sku_id,category,subcategory,units_sold,on_hand_units,on_order_units,lead_time_days,reorder_point,inventory_position,target_inventory,recommended_order_qty,inventory_risk,recommendation_priority,recommendation
0,2025-01-01,SKU001,Furniture,Chair,52.0,284.0,125,6.0,255,409.0,255,0,OVERSTOCK_RISK,LOW,NO_ACTION
1,2025-01-02,SKU001,Furniture,Chair,69.0,215.0,128,6.0,255,343.0,255,0,HEALTHY,LOW,NO_ACTION
2,2025-01-03,SKU001,Furniture,Chair,49.0,166.0,186,6.0,255,352.0,255,0,HEALTHY,LOW,NO_ACTION
3,2025-01-04,SKU001,Furniture,Chair,74.0,92.0,62,6.0,255,154.0,255,101,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
4,2025-01-05,SKU001,Furniture,Chair,43.0,49.0,112,6.0,255,161.0,255,94,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5,2025-01-06,SKU001,Furniture,Chair,56.0,50.0,0,6.0,255,50.0,255,205,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
6,2025-01-07,SKU001,Furniture,Chair,46.0,4.0,64,6.0,255,68.0,255,187,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
7,2025-01-08,SKU001,Furniture,Chair,51.0,0.0,127,6.0,255,127.0,255,128,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
8,2025-01-09,SKU001,Furniture,Chair,65.0,0.0,43,6.0,255,43.0,255,212,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
9,2025-01-10,SKU001,Furniture,Chair,70.0,0.0,49,6.0,255,49.0,255,206,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
10,2025-01-11,SKU001,Furniture,Chair,84.0,0.0,65,6.0,255,65.0,255,190,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
11,2025-01-12,SKU001,Furniture,Chair,59.0,51.0,0,6.0,255,51.0,255,204,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
12,2025-01-13,SKU001,Furniture,Chair,43.0,8.0,187,6.0,255,195.0,255,60,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
13,2025-01-14,SKU001,Furniture,Chair,66.0,0.0,139,6.0,255,139.0,255,116,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
14,2025-01-15,SKU001,Furniture,Chair,74.0,0.0,135,6.0,255,135.0,255,120,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
15,2025-01-16,SKU001,Furniture,Chair,50.0,0.0,87,6.0,255,87.0,255,168,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
16,2025-01-17,SKU001,Furniture,Chair,40.0,0.0,39,6.0,255,39.0,255,216,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
17,2025-01-18,SKU001,Furniture,Chair,58.0,101.0,0,6.0,255,101.0,255,154,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
18,2025-01-19,SKU001,Furniture,Chair,66.0,35.0,30,6.0,255,65.0,255,190,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
19,2025-01-20,SKU001,Furniture,Chair,41.0,0.0,149,6.0,255,149.0,255,106,STOCKOUT_RISK,HIGH,REPLENISH_STOCK

In [60]:
# Summarize recommendations

recommendation_summary = (
    inventory_recommendations[
        "recommendation"
    ]
    .value_counts()
    .reset_index()
)

recommendation_summary.columns = [
    "Recommendation",
    "Record_Count"
]

recommendation_summary["Percentage"] = (
    recommendation_summary["Record_Count"]
    / len(inventory_recommendations)
    * 100
)

recommendation_summary

    Recommendation  Record_Count  Percentage
0  REPLENISH_STOCK         19208    91.87793
1        NO_ACTION          1698     8.12207

In [61]:
# Summarize inventory risk

risk_summary = (
    inventory_recommendations[
        "inventory_risk"
    ]
    .value_counts()
    .reset_index()
)

risk_summary.columns = [
    "Inventory_Risk",
    "Record_Count"
]

risk_summary["Percentage"] = (
    risk_summary["Record_Count"]
    / len(inventory_recommendations)
    * 100
)

risk_summary

   Inventory_Risk  Record_Count  Percentage
0   STOCKOUT_RISK         19208   91.877930
1         HEALTHY          1033    4.941165
2  OVERSTOCK_RISK           665    3.180905

In [62]:
# Calculate total recommended replenishment quantity

total_recommended_units = (
    inventory_recommendations[
        "recommended_order_qty"
    ].sum()
)

print(
    "Total Recommended Replenishment Units:",
    int(total_recommended_units)
)

Total Recommended Replenishment Units: 4944578

In [63]:
# Create SKU-level inventory recommendation summary

sku_inventory_summary = (
    inventory_recommendations
    .groupby("sku_id")
    .agg(
        average_inventory_position=(
            "inventory_position",
            "mean"
        ),
        average_target_inventory=(
            "target_inventory",
            "mean"
        ),
        total_recommended_order_qty=(
            "recommended_order_qty",
            "sum"
        ),
        risk_records=(
            "inventory_risk",
            lambda x: (x != "HEALTHY").sum()
        )
    )
    .reset_index()
)

sku_inventory_summary.head(20)

,sku_id,average_inventory_position,average_target_inventory,total_recommended_order_qty,risk_records
0,SKU001,104.730769,255.0,82386,544
1,SKU002,51.615970,107.0,31006,524
2,SKU003,21.276557,48.0,14626,541
3,SKU004,113.044706,360.0,112977,420
4,SKU005,160.302198,460.0,163666,545
5,SKU006,24.783883,129.0,56902,546
6,SKU007,158.875458,417.0,141605,544
7,SKU008,186.527473,209.0,31686,388
8,SKU009,31.646520,57.0,13980,515
9,SKU010,96.345216,394.0,158650,533
10,SKU011,196.033771,1231.0,551637,533
11,SKU012,96.569597,237.0,77099,543
12,SKU013,37.137472,181.0,65480,444
13,SKU014,156.070370,690.0,288322,540
14,SKU015,142.875728,373.0,122739,511
15,SKU016,163.047619,255.0,56659,455
16,SKU017,145.314480,428.0,137876,438
17,SKU018,147.260073,786.0,348752,546
18,SKU019,71.736264,94.0,17485,399
19,SKU020,193.996078,774.0,297529,504

In [64]:
# Identify SKUs with the highest replenishment requirements

top_replenishment_skus = (
    sku_inventory_summary
    .sort_values(
        "total_recommended_order_qty",
        ascending=False
    )
    .head(20)
)

top_replenishment_skus

,sku_id,average_inventory_position,average_target_inventory,total_recommended_order_qty,risk_records
10,SKU011,196.033771,1231.0,551637,533
22,SKU023,181.626374,821.0,349098,546
17,SKU018,147.260073,786.0,348752,546
24,SKU025,119.514652,714.0,324589,546
19,SKU020,193.996078,774.0,297529,504
13,SKU014,156.070370,690.0,288322,540
34,SKU035,126.413919,604.0,260762,546
27,SKU028,122.353480,483.0,196913,546
26,SKU027,67.141026,391.0,176827,546
4,SKU005,160.302198,460.0,163666,545
20,SKU021,186.780242,495.0,163639,493
9,SKU010,96.345216,394.0,158650,533
6,SKU007,158.875458,417.0,141605,544
16,SKU017,145.314480,428.0,137876,438
14,SKU015,142.875728,373.0,122739,511
3,SKU004,113.044706,360.0,112977,420
35,SKU036,65.327839,264.0,108475,546
25,SKU026,175.631868,349.0,94984,539
0,SKU001,104.730769,255.0,82386,544
39,SKU040,122.970696,271.0,80948,544

In [65]:
# Identify SKUs with the highest number of risk records

top_risk_skus = (
    sku_inventory_summary
    .sort_values(
        "risk_records",
        ascending=False
    )
    .head(20)
)

top_risk_skus

,sku_id,average_inventory_position,average_target_inventory,total_recommended_order_qty,risk_records
5,SKU006,24.783883,129.0,56902,546
24,SKU025,119.514652,714.0,324589,546
27,SKU028,122.353480,483.0,196913,546
35,SKU036,65.327839,264.0,108475,546
34,SKU035,126.413919,604.0,260762,546
26,SKU027,67.141026,391.0,176827,546
17,SKU018,147.260073,786.0,348752,546
22,SKU023,181.626374,821.0,349098,546
4,SKU005,160.302198,460.0,163666,545
29,SKU030,88.582418,235.0,80179,545
39,SKU040,122.970696,271.0,80948,544
0,SKU001,104.730769,255.0,82386,544
6,SKU007,158.875458,417.0,141605,544
11,SKU012,96.569597,237.0,77099,543
2,SKU003,21.276557,48.0,14626,541
13,SKU014,156.070370,690.0,288322,540
25,SKU026,175.631868,349.0,94984,539
10,SKU011,196.033771,1231.0,551637,533
9,SKU010,96.345216,394.0,158650,533
1,SKU002,51.615970,107.0,31006,524

In [66]:
# Create processed-data directory if needed

os.makedirs(
    "../data/processed",
    exist_ok=True
)

# Export final recommendations

inventory_recommendations.to_csv(
    "../data/processed/inventory_recommendations.csv",
    index=False
)

print(
    "inventory_recommendations.csv "
    "exported successfully."
)

inventory_recommendations.csv exported successfully.

In [67]:
# Export SKU-level summary

sku_inventory_summary.to_csv(
    "../data/processed/sku_inventory_summary.csv",
    index=False
)

print(
    "sku_inventory_summary.csv "
    "exported successfully."
)

sku_inventory_summary.csv exported successfully.

In [68]:
# Export recommendation and risk summaries

recommendation_summary.to_csv(
    "../data/processed/inventory_recommendation_summary.csv",
    index=False
)

risk_summary.to_csv(
    "../data/processed/inventory_risk_summary.csv",
    index=False
)

print("Summary reports exported successfully.")

Summary reports exported successfully.

In [69]:
# Generate final inventory recommendation metrics

final_summary = pd.DataFrame({
    "Metric": [
        "Total Records",
        "Unique SKUs",
        "Total Recommended Order Units",
        "Stockout Risk Records",
        "Overstock Risk Records",
        "Healthy Records",
        "High Priority Records"
    ],
    "Value": [
        len(inventory_recommendations),

        inventory_recommendations[
            "sku_id"
        ].nunique(),

        int(
            inventory_recommendations[
                "recommended_order_qty"
            ].sum()
        ),

        (
            inventory_recommendations[
                "inventory_risk"
            ] == "STOCKOUT_RISK"
        ).sum(),

        (
            inventory_recommendations[
                "inventory_risk"
            ] == "OVERSTOCK_RISK"
        ).sum(),

        (
            inventory_recommendations[
                "inventory_risk"
            ] == "HEALTHY"
        ).sum(),

        (
            inventory_recommendations[
                "recommendation_priority"
            ] == "HIGH"
        ).sum()
    ]
})

final_summary

                          Metric    Value
0                  Total Records    20906
1                    Unique SKUs       40
2  Total Recommended Order Units  4944578
3          Stockout Risk Records    19208
4         Overstock Risk Records      665
5                Healthy Records     1033
6          High Priority Records    19208

In [70]:
# Show the most important recommendations first

final_priority_view = (
    inventory_recommendations
    .sort_values(
        [
            "recommendation_priority",
            "recommended_order_qty"
        ],
        ascending=[True, False]
    )
)

final_priority_view.head(30)

,date,sku_id,category,subcategory,units_sold,on_hand_units,on_order_units,lead_time_days,reorder_point,inventory_position,target_inventory,recommended_order_qty,inventory_risk,recommendation_priority,recommendation
5440,2025-05-28,SKU011,Small Appliances,Toaster,92.0,0.0,0,14.0,1231,0.0,1231,1231,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5471,2025-06-28,SKU011,Small Appliances,Toaster,118.0,0.0,0,14.0,1231,0.0,1231,1231,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5685,2026-01-28,SKU011,Small Appliances,Toaster,118.0,0.0,0,14.0,1231,0.0,1231,1231,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5744,2026-03-28,SKU011,Small Appliances,Toaster,143.0,0.0,0,14.0,1231,0.0,1231,1231,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5761,2026-04-14,SKU011,Small Appliances,Toaster,100.0,0.0,0,14.0,1231,0.0,1231,1231,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5836,2026-06-28,SKU011,Small Appliances,Toaster,122.0,0.0,0,14.0,1231,0.0,1231,1231,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5549,2025-09-14,SKU011,Small Appliances,Toaster,113.0,1.0,0,14.0,1231,1.0,1231,1230,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5579,2025-10-14,SKU011,Small Appliances,Toaster,107.0,11.0,0,14.0,1231,11.0,1231,1220,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5379,2025-03-28,SKU011,Small Appliances,Toaster,85.0,28.0,0,14.0,1231,28.0,1231,1203,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5426,2025-05-14,SKU011,Small Appliances,Toaster,108.0,30.0,0,14.0,1231,30.0,1231,1201,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5320,2025-01-28,SKU011,Small Appliances,Toaster,107.0,40.0,0,14.0,1231,40.0,1231,1191,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5351,2025-02-28,SKU011,Small Appliances,Toaster,112.0,43.0,0,14.0,1231,43.0,1231,1188,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5535,2025-08-31,SKU011,Small Appliances,Toaster,123.0,0.0,44,14.0,1231,44.0,1231,1187,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5423,2025-05-11,SKU011,Small Appliances,Toaster,96.0,0.0,45,14.0,1231,45.0,1231,1186,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5441,2025-05-29,SKU011,Small Appliances,Toaster,68.0,0.0,45,14.0,1231,45.0,1231,1186,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5806,2026-05-29,SKU011,Small Appliances,Toaster,88.0,0.0,45,14.0,1231,45.0,1231,1186,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5833,2026-06-25,SKU011,Small Appliances,Toaster,95.0,0.0,46,14.0,1231,46.0,1231,1185,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5340,2025-02-17,SKU011,Small Appliances,Toaster,88.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5419,2025-05-07,SKU011,Small Appliances,Toaster,104.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5452,2025-06-09,SKU011,Small Appliances,Toaster,82.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5603,2025-11-07,SKU011,Small Appliances,Toaster,94.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5658,2026-01-01,SKU011,Small Appliances,Toaster,97.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5665,2026-01-08,SKU011,Small Appliances,Toaster,117.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5753,2026-04-06,SKU011,Small Appliances,Toaster,81.0,0.0,47,14.0,1231,47.0,1231,1184,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5375,2025-03-24,SKU011,Small Appliances,Toaster,125.0,0.0,48,14.0,1231,48.0,1231,1183,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5487,2025-07-14,SKU011,Small Appliances,Toaster,99.0,48.0,0,14.0,1231,48.0,1231,1183,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5832,2026-06-24,SKU011,Small Appliances,Toaster,139.0,0.0,48,14.0,1231,48.0,1231,1183,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5315,2025-01-23,SKU011,Small Appliances,Toaster,102.0,0.0,49,14.0,1231,49.0,1231,1182,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5569,2025-10-04,SKU011,Small Appliances,Toaster,146.0,0.0,49,14.0,1231,49.0,1231,1182,STOCKOUT_RISK,HIGH,REPLENISH_STOCK
5805,2026-05-28,SKU011,Small Appliances,Toaster,125.0,49.0,0,14.0,1231,49.0,1231,1182,STOCKOUT_RISK,HIGH,REPLENISH_STOCK

# Conclusion

The Inventory Recommendation stage converts the FORESIGHT inventory and demand information into actionable replenishment recommendations.

The final outputs include:

- Inventory Position
- Reorder Point
- Target Inventory
- Recommended Order Quantity
- Inventory Risk
- Recommendation Priority
- Actionable Recommendation
- SKU-level Inventory Summary

The generated CSV files can now be used by the FORESIGHT dashboard and final project documentation.

### Output Files

- `inventory_recommendations.csv`
- `sku_inventory_summary.csv`
- `inventory_recommendation_summary.csv`
- `inventory_risk_summary.csv`

In [71]:
# Validate final inventory recommendations

print("Final dataset shape:", inventory_recommendations.shape)

print("\nMissing values in key recommendation fields:")
print(
    inventory_recommendations[
        [
            "inventory_position",
            "target_inventory",
            "recommended_order_qty",
            "inventory_risk",
            "recommendation"
        ]
    ].isnull().sum()
)

Final dataset shape: (20906, 15)

Missing values in key recommendation fields:
inventory_position       0
target_inventory         0
recommended_order_qty    0
inventory_risk           0
recommendation           0
dtype: int64

In [72]:
# Validate recommended order quantities

print("Minimum recommended order quantity:",
      inventory_recommendations["recommended_order_qty"].min())

print("Maximum recommended order quantity:",
      inventory_recommendations["recommended_order_qty"].max())

print("Total recommended order quantity:",
      inventory_recommendations["recommended_order_qty"].sum())

# Recommended quantity should never be negative
negative_qty = (
    inventory_recommendations["recommended_order_qty"] < 0
).sum()

print("Negative recommendation quantities:", negative_qty)

Minimum recommended order quantity: 0
Maximum recommended order quantity: 1231
Total recommended order quantity: 4944578
Negative recommendation quantities: 0

In [73]:
# Verify exported files

output_files = [
    "../data/processed/inventory_recommendations.csv",
    "../data/processed/sku_inventory_summary.csv",
    "../data/processed/inventory_recommendation_summary.csv",
    "../data/processed/inventory_risk_summary.csv"
]

print("Output file verification:\n")

for file in output_files:
    if os.path.exists(file):
        print("✅", file)
    else:
        print("❌ Missing:", file)

Output file verification:

✅ ../data/processed/inventory_recommendations.csv
✅ ../data/processed/sku_inventory_summary.csv
✅ ../data/processed/inventory_recommendation_summary.csv
✅ ../data/processed/inventory_risk_summary.csv

In [74]:
print("=" * 60)
print("06_inventory_recommendations.ipynb COMPLETED")
print("=" * 60)

print("\nMain output:")
print("inventory_recommendations.csv")

print("\nSupporting outputs:")
print("sku_inventory_summary.csv")
print("inventory_recommendation_summary.csv")
print("inventory_risk_summary.csv")

print("\nInventory recommendation pipeline completed successfully.")

============================================================
06_inventory_recommendations.ipynb COMPLETED
============================================================

Main output:
inventory_recommendations.csv

Supporting outputs:
sku_inventory_summary.csv
inventory_recommendation_summary.csv
inventory_risk_summary.csv

Inventory recommendation pipeline completed successfully.

notebooks/
│
├── 01_data_profiling.ipynb
├── 02_eda.ipynb
├── 03_feature_engineering.ipynb
├── 04_demand_forecasting.ipynb
├── 05_inventory_risk_analysis.ipynb
├── 06_inventory_recommendations.ipynb
├── 07_model_evaluation.ipynb
└── 08_final_analysis.ipynb